### ISSUE TITLE
install.sh does not gracefully handle redirection characters read from dshield.conf

### ISSUE THREAD

**Issue by BrianWGray** [DShield-ISC/dshield#1]
install.sh does not gracefully handle redirection characters read from dshield.conf
reading old configuration
./dshield/bin/install.sh: 1: /etc/dshield.conf: Syntax error: redirection unexpected

**Comment by rydogg1** [comment]
Yes.  Saw this too on an upgrade run through.  Ended up deleting /etc/dshield.conf and re-running the install.sh

**Comment by jullrich** [comment]
fixed. this was due to an error in the API as it didn't return the user id as expected. re-running install.sh will fix corrupt dshield.conf files now
