### ISSUE TITLE
Enhancement: Use Public IP as the Target IP

### ISSUE THREAD

**Issue by mikep11** [DShield-ISC/dshield#104]
I notice in the reports that the target IP is showing my private IP address.  Wouldn't it be more helpful to show the public IP that is being attacked?

Or is there a setting I missed?

**Comment by bgant** [comment]
It looks like /etc/dshield.ini has placeholders for this future work (honeypotip= and replacehoneypotip=).

In the meantime, I inserted three lines in the /srv/dshield/dshield.pl file after rsyslog is restarted and before the /var/log/dshield.log.old file is opened for parsing. The lines just lookup and replace my internal private IP with my external IP before the log is parsed:

```
`/etc/init.d/rsyslog restart`;
my $privateip=`hostname -I | tr -d ' \n'`;
my $internetip=`curl --silent http://ipecho.net/plain`;
`sed -i 's/DST=$privateip/DST=$internetip/g' /var/log/dshield.log.old`;
open(F,'/var/log/dshield.log.old');
```

**Comment by jullrich** [comment]
thanks for the solution. I will try to add that. We had some issues with hosts running IPv6 in which case the IPv6 address was reported. But with curl (or wget) I should be able to force IPv4. will try that.

**Comment by omnipotence407** [comment]
The solution by @bgant no longer works - it looks like dshield.pl is no longer called.
Has this feature been implemented and I need to enable it somewhere?

**Comment by jullrich** [comment]
added the public IP of the honeypot to the configuration (and may be used later). I am using our own API for it to avoid dependency issues.
