### ISSUE TITLE
404 & SSH Reports Not Uploading

### ISSUE THREAD

**Issue by ebrumm-cog** [DShield-ISC/dshield#105]
404 & SSH reports are not being reported on the dshield website,

Last 404 Log Received: 2018-05-01 17:09:55
Last ssh Log Received: 2018-04-24 15:15:10
Last ssh Firewall Log Received: 2018-05-06 05:20:08
Current Time/Date: 2018-05-05 22:46:35

Twice in the past week, I've run git pull, sudo bin/install.sh with the latest version, yet no 404 & SSH reports yet

**Comment by bgant** [comment]
To fix the SSH (and Telnet) reporting, it looks like we need to add "enabled = true" to the /srv/cowrie/cowrie.cfg file in the [output_dshield] section. That cleared up the cowrie errors and started up listeners on ports 2222 and 2223.

I also added "enabled = true" to the [output_mysql] section just in case, but I don't know enough about MySQL/MariaDB to test whether it is needed or not.

I have not really dived into the Web and 404 reporting yet to see why they are not working. Port 8000 is listening, but it doesn't look like port 80 is redirecting to it.

Here are the cowrie startup errors I had when running Raspbian Stretch Lite 2018-04-18 on a Raspberry Pi 2 with the default dshield.git installation:

May  4 22:54:45 raspberrypi cowrie[202]: Starting Cowrie Honeypot:Using default Python virtual environment "/srv/cowrie/cowrie-env"
May  4 22:54:45 raspberrypi cowrie[202]: Starting cowrie: [twistd   --umask 0022 --pidfile var/run/cowrie.pid --logger cowrie.python.logfile.logger cowrie ]...
May  4 22:56:11 raspberrypi cowrie[202]: Traceback (most recent call last):
May  4 22:56:11 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/bin/twistd", line 11, in <module>
May  4 22:56:11 raspberrypi cowrie[202]:     sys.exit(run())
May  4 22:56:11 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
May  4 22:56:11 raspberrypi cowrie[202]:     app.run(runApp, ServerOptions)
May  4 22:56:11 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
May  4 22:56:11 raspberrypi cowrie[202]:     runApp(config)
May  4 22:56:11 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
May  4 22:56:11 raspberrypi cowrie[202]:     runner.run()
May  4 22:56:12 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
May  4 22:56:12 raspberrypi cowrie[202]:     self.application = self.createOrGetApplication()
May  4 22:56:12 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
May  4 22:56:12 raspberrypi cowrie[202]:     ser = plg.makeService(self.config.subOptions)
May  4 22:56:12 raspberrypi cowrie[202]:   File "/srv/cowrie/twisted/plugins/cowrie_plugin.py", line 159, in makeService
May  4 22:56:12 raspberrypi cowrie[202]:     if CONFIG.getboolean(x, 'enabled') is False:
May  4 22:56:12 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
May  4 22:56:12 raspberrypi cowrie[202]:     **kwargs)
May  4 22:56:12 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
May  4 22:56:12 raspberrypi cowrie[202]:     return self._get(section, conv, option, **kwargs)
May  4 22:56:12 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
May  4 22:56:12 raspberrypi cowrie[202]:     return conv(self.get(section, option, **kwargs))
May  4 22:56:12 raspberrypi cowrie[202]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
May  4 22:56:12 raspberrypi cowrie[202]:     raise NoOptionError(option, section)
May  4 22:56:12 raspberrypi cowrie[202]: backports.configparser.NoOptionError: No option 'enabled' in section: u'output_dshield'
May  4 22:56:13 raspberrypi cowrie[202]:  failed!

**Comment by bgant** [comment]
I did some more digging around with the web server. It is listening on Port 8000 and appears to be working fine. The port redirects in /etc/network/iptables also are also working to send traffic to Port 8000.

The /srv/dshield/weblogsumit.py script also appears to be working. It lists the entries since the last submit, gets a 200 response code, and an "OK xxx byes received" message when it is run. I did notice that it is submitting the logs as type "webhoneypot".

I think the issue might be the dshield/bin/status.sh script just isn't getting the right information from the DShield API. Looking at the full XML response from the API, the "lastweblog" and "last404" sections are empty:

```
<?xml version="1.0" encoding="UTF-8"?>
<checkapikey>
<id>xxxxx</id><authkey><![CDATA[xxxxx]]></authkey><lastweblog></lastweblog><last404></last404><lastssh>2018-05-07 19:16:44</lastssh><lastreport>2018-05-07 20:10:02</lastreport><version>0.1</version><result>ok</result>
</checkapikey>
```

Does the API "checkapikey" need to be reworked to replace "lastweblog" and "last404" with a "webhoneypot" response?

**Comment by ebrumm-cog** [comment]
I added the "enabled = true" option to both the [output_dshield] and [output_mysql] sections of the /srv/cowrie/cowrie.cfg file. Followed this up with a reboot of the host. The ssh logs are now passing through properly and are being reported on the dshield website. Haven't seen any of the 4040 log entries being reported on the dshield website and running /install/dshield/bin/status.sh is still showing an older "Last 404 Log Received" date.

Last Web Log Received:
Last 404 Log Received: 2018-05-01 17:09:55
Last ssh Log Received: 2018-05-07 20:20:07
Last ssh Firewall Log Received: 2018-05-07 20:40:05
Current Time/Date: 2018-05-07 14:11:04

Immediately after the reboot, I tailed the /srv/cowrie/log/cowrie.log file and noted several occurrences of the following:

'output_mysql: MySQL Error: (1146, "Table \'cowrie.params\' doesn\'t exist")'

Not sure if that has any pertinence on the 404 log issue.

**Comment by bgant** [comment]
I looked through my cowrie.log files and don't see any MySQL errors. I am doing fresh installs, so it has only been up and running a few days.

**Comment by jullrich** [comment]
mysql should no longer be used/installed on the honyepot.

**Comment by gebhard73** [comment]
hmmm - then somebody must change install.sh and other configs to make this work w/o MySQL ...

**Comment by bgant** [comment]
MySQL (MariaDB package) is definitely installed by install.sh and listening on 127.0.0.1:3306.

It looks like cowrie has multiple logging options. The default and most verbose is /srv/cowrie/log/cowrie.log. 

**[output_jsonlog]** in /srv/cowrie/cowrie.cfg has "enabled = true" and is creating /srv/cowrie/log/cowrie.json logs.

**[output_mysql]** is listed twice in /srv/cowrie/cowrie.cfg. The first is the default in cowrie and is commented out. The second section at the end of the file is added by DShield was probably not working until I added "enabled = true".

**[ouput_dshield]** is listed twice in /srv/cowrie/cowrie.cfg. The first is the default in cowrie and is commented out. The second section at the end of the file is added by DShield and appears to be working fine.

So it looks like we should set "enabled = false" in the [output_jsonlog] and [output_mysql] sections of /srv/cowrie/cowrie.cfg to reduce duplicate logging.

**Comment by gebhard73** [comment]
Thanks - I'll have a look into this when (if?) I can spare a little time :-/

**Comment by freekdk** [comment]
enabled = true or false is necessary after each [output_<something>] by a recent change in the cowrie software, otherwise telnet and ssh ports are not listening.
After making the changes to the original install.sh without taking into account the other commends, the diff shows:
`> diff -U0 dshield/bin/install.sh.new dshield/bin/install.sh`
`--- dshield/bin/install.sh.new  2018-05-11 18:29:40.639116692 +0200`
`+++ dshield/bin/install.sh      2018-05-09 13:01:00.386999862 +0200`
`@@ -1545 +1544,0 @@`
`-enabled = true`
`@@ -1550 +1548,0 @@`
`-enabled = true`
In view of the other commends the second true may need to be false, but also the one after [output_jsonlog].

**Comment by jullrich** [comment]
applied the "enabled = true" fix (also removed last mysql remnants). (version 0.48)

**Comment by jullrich** [comment]
appears to be working now. closing this issue.
