### ISSUE TITLE
bin/status.sh fails after last update.

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#107]
Looks like the /etc/dshield.conf file was deleted (and needed by the status.sh script)

I copied /etc/dshield.conf.2018-05-18_134354 to /etc/dshield.conf and the script worked again.

The /etc/dshield.ini file does not contain the same info as the /etc/dshield.conf file.. was that intentional?  If so, then the bin/status.sh needs to change to reflect that...

**Comment by jullrich** [comment]
Thanks! fixed it. Status.sh now looks for dshield.ini instead of the old dshield.conf. I also added a check that the e-mail address is present in dshield.ini
