### ISSUE TITLE
Starting cowrie gives error about output engine: kafka

### ISSUE THREAD

**Issue by freekdk** [DShield-ISC/dshield#109]
After starting cowrie using "systemctl restart cowrie.service" I got the following output:
jun 19 12:47:15 rpi1tumhon systemd[1]: Starting Cowrie SSH and Telnet Honeypot...
jun 19 12:47:15 rpi1tumhon cowrie[3980]: Using default Python virtual environment "/srv/cowrie/cowrie-env"
jun 19 12:47:15 rpi1tumhon cowrie[3980]: Starting cowrie: [twistd   --umask 0022 --pidfile var/run/cowrie.pid --logger cowrie.python
jun 19 12:47:38 rpi1tumhon cowrie[3980]: 'Failed to load output engine: kafka due to ImportError: No module named afkak.client'
jun 19 12:47:40 rpi1tumhon systemd[1]: Started Cowrie SSH and Telnet Honeypot.

I found kafka mentioned in /srv/cowrie/requirements-output.txt which is not used anymore in the latest install.sh. It looks however that the system is working.

Also /srv/cowrie/log/cowrie.log contains:
2018-06-19T12:01:08.920392+0200 [-] Twisted Version 18.4.0
2018-06-19T12:01:08.973351+0200 [-] Loaded output engine: jsonlog
2018-06-19T12:01:08.983973+0200 [-] 'Failed to load output engine: kafka due to ImportError: No module named afkak.client'
2018-06-19T12:01:08.991970+0200 [-] Please install the dependencies for kafka listed in requirements-output.txt
2018-06-19T12:01:10.081312+0200 [-] Loaded output engine: dshield

**Comment by jullrich** [comment]
actually that change should not affect any Kippo dependencies. "Kafka" is an odd dependency as we never used that. Looks like maybe a newer Cowrie version left that enabled in the configuration file as an output module. Will reinstall myself to verify.

**Comment by gebhard73** [comment]
as far as I can see the whole output requirements section has been commented out... ? I think this may be a problem ....

**Comment by jullrich** [comment]
looks like the cowrie requirements file was updated yesterday to include Kafka. The output section being commented out is ok as we add our own dshield section in the end. Installing now to see if the addition of kafka to the requirements "sticks".

**Comment by jullrich** [comment]
ok. I installed it and reproduced the error. the "output_kafka" section in the cowrie configuration file was not commented out. Once I removed the section, it started fine. I consider this a bug in cowrie. To fix it, I think it is best to use our own configuration file instead of modifying the sample one. This will give us more resilience down the road hopefully.

**Comment by freekdk** [comment]
Commented out the kafka section in /src/cowrie/cowrie.cfg which solved the problem. No error messages anymore.

**Comment by jullrich** [comment]
I made the next version live which will create the cowrie.cfg file from scratch. With that, I also added some customizations to the file to make it a bit more difficult to detect the honeypot.
