### ISSUE TITLE
What to do after install

### ISSUE THREAD

**Issue by jezkerwin** [DShield-ISC/dshield#11]
I've followed the instructions on the ISC diary entry, but it's a little unclear about what to do after the installation to make sure it's working.

Are there any additional steps that need to be taken after install?

**Comment by jmb1304** [comment]
I had to run Jekyll again after I ran devploy but I edited the script on my
system so I can just run devploy, but you have to be root. If that has not
been changed it would be helpful if you could.

**Comment by jezkerwin** [comment]
Sorry, you've lost me there.
What's jekyll and devploy?

**Comment by jmb1304** [comment]
I apologize, i was thinking about another piece of software like this one. There should not be anything that you need to do other than restart your pi / computer and port forward port 22 to the internet for the honeypot to work. I'm sorry for the mix-up.

**Comment by jullrich** [comment]
nothing has to be done. there is a "status.sh" script that you can run to make sure things are ok (do so after a couple hours, to make sure there was some data to report). You can also log into your account at isc.sans.edu (or dshield.org) to see if any reports are reaching the system.
