### ISSUE TITLE
bin/install.sh aborts 

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#110]
```
bin/install.sh: line 1565: syntax error near unexpected token `"mv /etc/cron.daily/logrotate /etc/cron.hourly"'
bin/install.sh: line 1565: `run("mv /etc/cron.daily/logrotate /etc/cron.hourly")'
```
install log finished with:
```
2018-06-21_023624 ### Running: mkdir /var/run/dshield
mkdir: cannot create directory ‘/var/run/dshield’: File exists
2018-06-21_023624 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (1)!
2018-06-21_023624 ### DEBUG OUTPUT: copying /home/pi/dshield/bin/../etc/logrotate.d/dshield to /etc/logrotate.d and chmod to 644
2018-06-21_023624 ### Running: cp /home/pi/dshield/bin/../etc/logrotate.d/dshield /etc/logrotate.d
2018-06-21_023624 ### Running: chmod 644 /etc/logrotate.d/dshield
```

This happened with

git pull
sudo bin/install.sh

on existing honeypot (2018-04-18-raspbian-stretch-lite base).

I ran 
```
sudo mv /etc/cron.daily/logrotate /etc/cron.hourly
```
to finish the update and rebooted.. It seems to run ok after reboot, but the install.sh script should be fixed.

**Comment by jullrich** [comment]
just pushed a fix live. Let me know if it works. That newer version of the install.sh file also fixes a couple dshield.ini issues that didn't matter so far (some variables that are not used yet got written to the wrong file). If you have a file /dev/dshield.ini, then please delete it.

**Comment by ktrue** [comment]
No /dev/dshield.ini file to delete.
Running the install.sh now... will report results shortly.

**Comment by ktrue** [comment]
install.sh now completes successfully :)
