### ISSUE TITLE
Clarification Request - Enabled Ports and Services

### ISSUE THREAD

**Issue by dmblack** [DShield-ISC/dshield#113]
Hello Team,

Whilst deploying this solution on a raspberry pi, I've noticed that the documentation and requirements do not clearly align. Additionally; it's not something that may be quickly observed or reviewed in a fresh deployment.

The documentation suggests exposing all ports, perhaps via DMZ)[0], of the endpoint to the wild - though then later suggests that only the SSH honeypot is enabled.[1][2]

[0] https://github.com/DShield-ISC/dshield/blame/master/README.md#L100
[1] https://github.com/DShield-ISC/dshield/blame/master/README.md#L110
[2] https://github.com/DShield-ISC/dshield/blame/master/README.md#L214

It seems unnecessary to open this to the wild, if the only service enabled is SSH - as per [2].

I took a moment to review running services, enabled network services, and firewall rules - but it's not clear, and I have not yet had time to familiarize myself with the code...

May we have clarification on what this raspberry pi configuration currently deploys. I'm happy to assist in this, but need a bit of support to begin.

Thanks in advance.

**Comment by gebhard73** [comment]
Honeypot runs on specific ports (e.g. for ssh, telnet, and a fake webserver), but all other ports are needed to assist dshield data collection, so the host should be fully exposed.
Suggestion: have a look at the firewall part of the installation script.

**Comment by dmblack** [comment]
@gebhard73 
I appreciate your response.

I had an opportunity to review the tool further, starting to identify the ports you suggested - all part of the single honeypot (Cowrie?).

I had not yet discovered the rest of the ports are logged and reported, though started to see some information relevant in the information submitted and then visible in my profile.

I found, more so, relevant information on the isc.sans.edu website - but again; hard to correlate that directly with what was deployed running the script and with README.md

I'll further expose my asset, and propose some edits for lesser `in the know` users like myself.

Thanks for your effort, again! Marking as closed.

**Comment by gebhard73** [comment]
Here you can find the section I was referring to in the installation script:
https://github.com/DShield-ISC/dshield/blob/d60069628e804153b09dce9fbff46fc51fce1530/bin/install.sh#L84-L98
https://github.com/DShield-ISC/dshield/blob/d60069628e804153b09dce9fbff46fc51fce1530/bin/install.sh#L656-L701

The Pi consist of four components:
- cowrie honeypot (exposed ssh, telnet, but other ports on the outside than on the inside of the device); things are reported to dshield
- ssh daemon (on non standard port, access only allowed from trusted networks); for admin access
- web script for simulating web server (again on other port on the outside than on the inside of the device);  for dshield's 404 project
- the rest is logged via iptables for reporting to dshield

Hope this could shed some light into your questions.

**Comment by dmblack** [comment]
@gebhard73 
Thanks for additional clarification. I really appreciate it.

I hope you understand my confusion, mostly around the README.md content.

One last point you may be able to shed some light on;

Where is the port redirection happening? I noticed the services are listening on ports like 2222, 2223, 8000, etc - and iptables is configured to appropriately accept those connections - but I don't see the relationship with the incoming (external) connection on the standard port of 22 being redirected to 2222?

Once more; I appreciate your effort and time!

**Comment by gebhard73** [comment]
The redirection is done via iptables in the prerouting chain. I suggest you grap a Pi, run the script and analyze the generated firewall script (based on your input). This is easier to follow than going through the script.

**Comment by dmblack** [comment]
@gebhard73 

Doh! I'm sorry. My syntax was wrong with IPTABLES (Version issues). I did check the rules, but I did not list the nat table properly.

I understand now. Again; I appreciate your feedback.
