### ISSUE TITLE
Raspian / Debian Stretch system version of PIP is broken and causes the installer to fail

### ISSUE THREAD

**Issue by Cruc1bl3** [DShield-ISC/dshield#116]
I'm using a RP B+ with the Raspbian "Stretch" distro installed. This release has a major issue in that the PIP version is very old which causes the honeynet installer to fail. Any attempt to update PIP via the normal mechanisms fails.
e.g. 
    sudo pip install --upgrade pip

Will fail with an error about missing methods.

This is a particular problem when using the honeynet installer as this calls PIP multiple times. The installer will fail repeatably with a traceback from PIP. The distro version is something like v9 and the current version is 18+. The manual fix, to install all the python libraries didn't help as the installer will still run pip and abort when it gets the error message.

The only solution that worked for me was to use the PIP bootstrap code from https://bootstrap.pypa.io/get-pip.py to install the latest PIP version.

e.g.    wget https://bootstrap.pypa.io/get-pip.py
         chmod +x get-pip.py
         ./get-pip.py

Once this has finished the honeynet installer works correctly.

Perhaps this is worth adding to the readme with the project to save others the same grief.

**Comment by gebhard73** [comment]
Hi,

this should have been handled by the installer script:
https://github.com/DShield-ISC/dshield/blob/f3cee0bc7a6b0800175f8cfcb4e25b8f55a8597e/bin/install.sh#L457-L503

Can you please provide the sanitized installation logs? Thanks.
