### ISSUE TITLE
Question: how can i set this up as an internal honeypot

### ISSUE THREAD

**Issue by ahiguero** [DShield-ISC/dshield#117]
we int he office are exploring the idea of using this as an internal honey pot i other words, report on possible internal scanners. so the questions of course are:

- do we still need the dshield account for this?

- what other changes to the iptables would be needed?

**Comment by gebhard73** [comment]
Hi,
the idea of this distribution is to have a Pi acting as a dshield sensor and providing information from attacks on telnet / ssh / web to the ISC so it helps the community reporting external threats (in the wild Internet). It is not meant to be or to be used as an internal honeypot. 

If you want to set up an internal honeypot you should look around for other distributions or install Cowrie or similar on a device.
