### ISSUE TITLE
What do i need to check to make sure that my 404 logs are working 

### ISSUE THREAD

**Issue by ahiguero** [DShield-ISC/dshield#118]
when i do the status check i see that that my 404 logs are not loading

Last 404 Log Received: 2018-08-23 04:23:58
Last ssh Log Received: 2018-08-28 01:52:26
Last ssh Firewall Log Received: 2018-08-28 01:24:02

**Comment by gebhard73** [comment]
Hi, the safest way is to look it up on the dhield status page
My Account -> My Reports
https://dshield.org/myreports.html

This should be identical with the status output you get on the Pi.

It happens from time to time that the mini web server stops working any need to be restarted. You may verify it by trying to access your public IP the sensor is running at from a browser using another public IP, e.g. your mobile.
