### ISSUE TITLE
Cowrie Failing to Start

### ISSUE THREAD

**Issue by omnipotence407** [DShield-ISC/dshield#119]
Checked the syslog after updating my honeypot and saw that Cowrie was failing to start and was in an endless loop of trying to start. (Solution below syslog printout of one iteration)

> Sep  1 04:48:31 honeypot systemd[1]: Starting Cowrie SSH and Telnet Honeypot...
> Sep  1 04:48:32 honeypot cowrie[17187]: Join the Cowrie community at: http://bit.ly/cowrieslack
> Sep  1 04:48:32 honeypot cowrie[17187]: Using default Python virtual environment "/srv/cowrie/cowrie-env"
> Sep  1 04:48:32 honeypot cowrie[17187]: Starting cowrie: [twistd   --umask 0022 --pidfile var/run/cowrie.pid --logger cowrie.python.logfile.logger cowrie ]...
> Sep  1 04:49:19 honeypot cowrie[17187]: Unhandled Error
> Sep  1 04:49:19 honeypot cowrie[17187]: Traceback (most recent call last):
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
> Sep  1 04:49:19 honeypot cowrie[17187]:     runApp(config)
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
> Sep  1 04:49:19 honeypot cowrie[17187]:     runner.run()
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
> Sep  1 04:49:19 honeypot cowrie[17187]:     self.application = self.createOrGetApplication()
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
> Sep  1 04:49:19 honeypot cowrie[17187]:     ser = plg.makeService(self.config.subOptions)
> Sep  1 04:49:19 honeypot cowrie[17187]: --- <exception caught here> ---
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/src/twisted/plugins/cowrie_plugin.py", line 152, in makeService
> Sep  1 04:49:19 honeypot cowrie[17187]:     globals(), locals(), ['output']).Output()
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/src/cowrie/output/jsonlog.py", line 49, in __init__
> Sep  1 04:49:19 honeypot cowrie[17187]:     self.outfile = cowrie.python.logfile.CowrieDailyLogFile(base, dirs, defaultMode=0o664)
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
> Sep  1 04:49:19 honeypot cowrie[17187]:     self._openFile()
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 248, in _openFile
> Sep  1 04:49:19 honeypot cowrie[17187]:     BaseLogFile._openFile(self)
> Sep  1 04:49:19 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 81, in _openFile
> Sep  1 04:49:19 honeypot cowrie[17187]:     self._file = open(self.path, "wb+", 0)
> Sep  1 04:49:19 honeypot cowrie[17187]: exceptions.IOError: [Errno 2] No such file or directory: u'log/cowrie.json'
> Sep  1 04:49:21 honeypot cowrie[17187]: Traceback (most recent call last):
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/bin/twistd", line 11, in <module>
> Sep  1 04:49:21 honeypot cowrie[17187]:     sys.exit(run())
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 31, in run
> Sep  1 04:49:21 honeypot cowrie[17187]:     app.run(runApp, ServerOptions)
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
> Sep  1 04:49:21 honeypot cowrie[17187]:     runApp(config)
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
> Sep  1 04:49:21 honeypot cowrie[17187]:     runner.run()
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 383, in run
> Sep  1 04:49:21 honeypot cowrie[17187]:     self.logger.start(self.application)
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 184, in start
> Sep  1 04:49:21 honeypot cowrie[17187]:     observer = self._observerFactory()
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/src/cowrie/python/logfile.py", line 37, in logger
> Sep  1 04:49:21 honeypot cowrie[17187]:     logfile = CowrieDailyLogFile("cowrie.log", dir)
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
> Sep  1 04:49:21 honeypot cowrie[17187]:     self._openFile()
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 248, in _openFile
> Sep  1 04:49:21 honeypot cowrie[17187]:     BaseLogFile._openFile(self)
> Sep  1 04:49:21 honeypot cowrie[17187]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 85, in _openFile
> Sep  1 04:49:21 honeypot cowrie[17187]:     self._file = open(self.path, "wb+", 0)
> Sep  1 04:49:21 honeypot cowrie[17187]: IOError: [Errno 2] No such file or directory: u'log/cowrie.log'
> Sep  1 04:49:23 honeypot systemd[1]: cowrie.service: Control process exited, code=exited status=1
> Sep  1 04:49:23 honeypot systemd[1]: Failed to start Cowrie SSH and Telnet Honeypot.
> Sep  1 04:49:23 honeypot systemd[1]: cowrie.service: Unit entered failed state.
> Sep  1 04:49:23 honeypot systemd[1]: cowrie.service: Failed with result 'exit-code'.
> Sep  1 04:49:23 honeypot systemd[1]: cowrie.service: Service hold-off time over, scheduling restart.
> Sep  1 04:49:23 honeypot systemd[1]: Stopped Cowrie SSH and Telnet Honeypot.

Note: line numbers may be off due to debugging lines I had to put in - but they should be within 5 or so.

Manual fix for me ended up being:
```
sudo mkdir /srv/cowrie/log
sudo chown cowrie:cowrie /srv/cowrie/log
```
Possible long-term fix:
Added the code below into the top of the else statement in _openFile(self) in /srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py 
```
            try: 
                os.makedirs(os.path.dirname(self.path))
            except OSError as exc: # Guard against race condition
                if exc.errno != errno.EEXIST:
                    raise
```
(Shamelessly stolen from [https://stackoverflow.com/a/12517490])

**Comment by mitrules** [comment]
I noticed the same thing but it goes a little deeper.   In addition, it does not create the /srv/cowrie/log/tty folder either.   After creating the log and log/tty folders Telnet process works like it is supposed to taking in logins and passwords.   The ssh side does not.   The process starts but never presents encryption options to the client therefore, never getting a login.   I have done several fresh installs and always the same end result.

Here is a good example:
2018-09-02T13:31:38.497757+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-09-02T13:31:38.514973+0000 [-] CowrieSSHFactory starting on 2222
2018-09-02T13:31:38.516967+0000 [cowrie.ssh.factory.CowrieSSHFactory#info] Starting factory <cowrie.ssh.factory.CowrieSSHFactory instance at 0x75152df0>
2018-09-02T13:31:38.578845+0000 [-] Ready to accept SSH connections
2018-09-02T13:31:38.581991+0000 [-] HoneyPotTelnetFactory starting on 2223
2018-09-02T13:31:38.582793+0000 [cowrie.telnet.transport.HoneyPotTelnetFactory#info] Starting factory <cowrie.telnet.transport.HoneyPotTelnetFactory instance at 0x75152d28>
2018-09-02T13:31:38.583842+0000 [-] Ready to accept Telnet connections
2018-09-02T13:31:50.128615+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 116.31.116.42:30420 (10.100.205.8:2222) [session: b4ad6918c575]
2018-09-02T13:31:50.143108+0000 [HoneyPotSSHTransport,0,116.31.116.42] Remote SSH version: 'SSH-2.0-PUTTY'
2018-09-02T13:31:55.124634+0000 [HoneyPotSSHTransport,0,116.31.116.42] Got remote error, code 11
	reason: 
2018-09-02T13:31:55.127873+0000 [HoneyPotSSHTransport,0,116.31.116.42] connection lost
2018-09-02T13:31:55.129514+0000 [HoneyPotSSHTransport,0,116.31.116.42] Connection lost after 4 seconds
2018-09-02T13:32:04.327397+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 172.58.136.83:47510 (10.100.205.8:2222) [session: 2f1b5317d946]
2018-09-02T13:32:04.366829+0000 [HoneyPotSSHTransport,1,172.58.136.83] Remote SSH version: 'SSH-2.0-PuTTY_Release_0.70'
2018-09-02T13:32:06.742197+0000 [HoneyPotSSHTransport,1,172.58.136.83] connection lost
2018-09-02T13:32:06.743841+0000 [HoneyPotSSHTransport,1,172.58.136.83] Connection lost after 2 seconds
2018-09-02T13:32:18.245894+0000 [cowrie.telnet.transport.HoneyPotTelnetFactory] New connection: 172.58.136.71:47557 (10.100.205.8:2223) [session: f014f42122c6]
2018-09-02T13:32:22.624149+0000 [CowrieTelnetTransport,0,172.58.136.71] first time for 172.58.136.71, need: 4
2018-09-02T13:32:22.625811+0000 [CowrieTelnetTransport,0,172.58.136.71] login attempt: 1
2018-09-02T13:32:22.656080+0000 [CowrieTelnetTransport,0,172.58.136.71] login attempt [admin/admin] failed
2018-09-02T13:32:22.703695+0000 [CowrieTelnetTransport,0,172.58.136.71] Warning: state changed and new state returned
2018-09-02T13:32:23.343025+0000 [-] dshield: SUCCESS: Sent 52 bytes worth of data to secure.dshield.org
2018-09-02T13:32:31.087772+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 5.94.193.45:62561 (10.100.205.8:2222) [session: ebd1e89e7e99]
2018-09-02T13:32:31.102537+0000 [HoneyPotSSHTransport,2,5.94.193.45] Remote SSH version: 'SSH-2.0-libssh2_1.8.0'
2018-09-02T13:32:31.291683+0000 [HoneyPotSSHTransport,2,5.94.193.45] connection lost
2018-09-02T13:32:31.293278+0000 [HoneyPotSSHTransport,2,5.94.193.45] Connection lost after 0 seconds
2018-09-02T13:32:33.022998+0000 [CowrieTelnetTransport,0,172.58.136.71] Connection lost after 14 seconds
2018-09-02T13:32:43.034895+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 172.58.136.71:29204 (10.100.205.8:2222) [session: b38ebe23b43d]
2018-09-02T13:32:43.049454+0000 [HoneyPotSSHTransport,3,172.58.136.71] Remote SSH version: 'SSH-2.0-PuTTY_Release_0.70'
2018-09-02T13:32:43.344644+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 61.184.247.10:55561 (10.100.205.8:2222) [session: 2f3677b61751]
2018-09-02T13:32:43.359399+0000 [HoneyPotSSHTransport,4,61.184.247.10] Remote SSH version: 'SSH-2.0-PUTTY'
2018-09-02T13:32:43.608521+0000 [HoneyPotSSHTransport,4,61.184.247.10] Got remote error, code 11
	reason: 
2018-09-02T13:32:43.611244+0000 [HoneyPotSSHTransport,4,61.184.247.10] connection lost
2018-09-02T13:32:43.612957+0000 [HoneyPotSSHTransport,4,61.184.247.10] Connection lost after 0 seconds
2018-09-02T13:32:45.218371+0000 [HoneyPotSSHTransport,3,172.58.136.71] connection lost
2018-09-02T13:32:45.220046+0000 [HoneyPotSSHTransport,3,172.58.136.71] Connection lost after 2 seconds
2018-09-02T13:32:51.576108+0000 [cowrie.ssh.factory.CowrieSSHFactory] New connection: 182.61.38.45:46008 (10.100.205.8:2222) [session: 0de531007f99]

**Comment by ahiguero** [comment]
Good finding, do you know if your reports are now working after this change?

**Comment by cgajones** [comment]
Had the same issues with SSH today.
a) the string used in cowrie.cfg for the SSH version, isn't liked for some reason.
Changed from 
`version = OpenSSH_7.4p1 Raspbian-10+deb9u4`
to 
`version = SSH-2.0-OpenSSH_7.3p1 Ubuntu-1`
b) armv7l is missing as an architecture in /srv/cowrie/share/cowrie/arch. I copied linux-arm-msb to armv7l

Also, the dl folder is missing from /srv/cowrie/var/lib/cowrie/downloads/

So far so good....

**Comment by omnipotence407** [comment]
Reports worked for me the first day, but then they stopped.  I had the same errors in the log as mitrules.

I will try cgajones' fix (a) now.
- Based on the cowrie sample config:
> # SSH version string as present to the client.
> # Version string MUST start with SSH-2.0- or SSH-1.99-

But, turns out cowrie hasn't been working since I posted before:
"exceptions.NameError: global name 'errno' is not defined"
I added "errno" to the inport line in this file:
"/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py"
and it started right up.

Next error, from /srv/cowrie/log/cowrie.log: (times removed to make it easier to read, errored out almost exactly 10 min after start)
> [-] Python Version 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
> [-] Twisted Version 18.7.0
> [-] Loaded output engine: jsonlog
> [-] Loaded output engine: dshield
> [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.7.0 (/srv/cowrie/cowrie-env/bin/python2 2.7.13) starting up.
> [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
> [-] CowrieSSHFactory starting on 2222
> [cowrie.ssh.factory.CowrieSSHFactory#info] Starting factory <cowrie.ssh.factory.CowrieSSHFactory instance at 0xb5120ee0>
> [-] Ready to accept SSH connections
> [-] HoneyPotTelnetFactory starting on 2223
> [cowrie.telnet.transport.HoneyPotTelnetFactory#info] Starting factory <cowrie.telnet.transport.HoneyPotTelnetFactory instance at 0xb5120be8>
> [-] Ready to accept Telnet connections
> [-] Received SIGTERM, shutting down.
> [-] Received SIGTERM, shutting down.
> [-] Unhandled Error /
>         Traceback (most recent call last):
>           File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 399, in startReactor
>             self.config, oldstdout, oldstderr, self.profiler, reactor)
>           File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 312, in runReactorWithLogging
>             reactor.run()
>           File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
>             self.mainLoop()
>           File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1270, in mainLoop
>             self.runUntilCurrent()
>         --- <exception caught here> ---
>           File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 869, in runUntilCurrent
>             f(*a, **kw)
>           File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/internet/base.py", line 630, in stop
>             "Can't stop reactor that isn't running.")
>         twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
> 
> [-] (TCP Port 2223 Closed)
> [cowrie.telnet.transport.HoneyPotTelnetFactory#info] Stopping factory <cowrie.telnet.transport.HoneyPotTelnetFactory instance at 0xb5120be8>
> [-] (TCP Port 2222 Closed)
> [cowrie.ssh.factory.CowrieSSHFactory#info] Stopping factory <cowrie.ssh.factory.CowrieSSHFactory instance at 0xb5120ee0>
> [-] Main loop terminated.
> [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.

After a reboot - telnet side worked for a minute, then stopped.  Nothing shown on the SSH side.  Also, all systems show that it is running, but nothing (except firewall) is happening in the logs that I am checking.
/var/log/dshield.log
/var/log/syslog
/srv/cowrie/log (cowrie.json and cowrie.log)

I'm at my limit for troubleshooting without any additional logs to check.

**Comment by ahiguero** [comment]
I did rebuild the pi a couple fo days ago, only the cowrie change needed to be done and stats it... my reports have been working daily with no issue

**Comment by cgajones** [comment]
@omnipotence407 if you can do a clean install, do.
Whilst its not quite 24 hours later here, it is next day, things are still working with just the changes I noted above.
According to the dshield stats, the last reports:
`Firewall reports: 2018-09-09 09:13:52
ssh/kippo reports: 2018-09-09 08:55:32
404 logs: 2018-09-09 09:13:52`

**Comment by omnipotence407** [comment]
Without rebuilding - I decided to let it go for a little while - and everything seems to be working now.

Only changes I made were as listed above.

**Comment by jullrich** [comment]
fixed the install script to properly copy cowrie 1.4.1 using the new github URL.
