### ISSUE TITLE
RPi2b+raspian-Jessie-lite collector working, but not submitting to dshield

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#12]
I show data is being collected using status.sh, but it never shows up in dshield.

![2016-02-26_dshield](https://cloud.githubusercontent.com/assets/17507343/13370330/1409642e-dcb9-11e5-8d3c-081ffad2880c.jpg)

I see entries in /var/log/dshield.log and in /var/log/mini-httpd.log for 404s and in /srv/cowrie/log both cowrie.json and cowrie.log are updating.  I think I'm getting traffic, it's just not auto-uploading to dshield.

What should I check out to get it to update to dshield regularly?

Best regards,
Ken

**Comment by ktrue** [comment]
I did:
cd dshield
git pull
sudo bin/install.sh

to refresh with today's distribution, and I see an SSH report was Received.  No Web or 404 Received yet, but there's hope :)

**Comment by jezkerwin** [comment]
I also see an SSH report but no Web or 404. I'm assuming we just wait for those to come in.

**Comment by jullrich** [comment]
The web server is not yet configured. But cowrie should already send logs. You should see firewall logs from /var/log/dshield.log being submitted twice an hour. cowrie uses the mechanism built into cowrie to submit logs.

**Comment by ktrue** [comment]
Ahh... that explains it.

I do show:

Last Report:	Firewall reports: 2016-02-28 04:15:05
ssh/kippo reports: 2016-02-28 04:20:24
Today's Firewall Reports:	219 Lines

so it is working.. thanks.  I'm looking forward to updates that make the Web and 404 reports available too.
