### ISSUE TITLE
webpy gives error and needs restart

### ISSUE THREAD

**Issue by freekdk** [DShield-ISC/dshield#120]
I found the following error messages with "journalctl -u webpy". The application reports "Error database is locked:". After a restart of webpy, things are normal again.

> sep 12 09:16:35 rpi1tumhon python[4757]: 59.3.132.25 - - [12/Sep/2018 09:16:35] "POST /GponForm/diag_Form?images/ HTTP/1.1" 200 -
sep 12 09:16:35 rpi1tumhon python[4757]: Traceback (most recent call last):
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
sep 12 09:16:35 rpi1tumhon python[4757]:     self.process_request(request, client_address)
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
sep 12 09:16:35 rpi1tumhon python[4757]:     self.finish_request(request, client_address)
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
sep 12 09:16:35 rpi1tumhon python[4757]:     self.RequestHandlerClass(request, client_address, self)
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
sep 12 09:16:35 rpi1tumhon python[4757]:     self.handle()
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
sep 12 09:16:35 rpi1tumhon python[4757]:     self.handle_one_request()
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
sep 12 09:16:35 rpi1tumhon python[4757]:     method()
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/srv/www/bin/web.py", line 250, in do_POST
sep 12 09:16:35 rpi1tumhon python[4757]:     length = int(self.headers['content-length'])
sep 12 09:16:35 rpi1tumhon python[4757]:   File "/usr/lib/python2.7/rfc822.py", line 393, in __getitem__
sep 12 09:16:35 rpi1tumhon python[4757]:     return self.dict[name.lower()]
sep 12 09:16:35 rpi1tumhon python[4757]: KeyError: 'content-length'
sep 12 09:32:32 rpi1tumhon python[4757]: 100.34.172.20 - - [12/Sep/2018 09:32:32] code 400, message Bad request version ('MCTP/1.0')
sep 12 09:32:32 rpi1tumhon python[4757]: 100.34.172.20 - - [12/Sep/2018 09:32:32] "REMOTE HI_SRDK_DEV_GetHddInfo MCTP/1.0" 400 -
sep 12 10:02:13 rpi1tumhon systemd[1]: Stopping DShield Web Honeypot...
sep 12 10:02:13 rpi1tumhon systemd[1]: Stopped DShield Web Honeypot.

>

**Comment by ahiguero** [comment]
for me after fully rebuilding the pi it just does not start... i see several exceptions but stoping and starting the service does not work

**Comment by ahiguero** [comment]
this is something that could be related with the dist-packages being used i have reported it on the slack channel

**Comment by ahiguero** [comment]
to add tot he previous message i have installed and compiled version 2.7.9 and still the issue remains

**Comment by jullrich** [comment]
bad fix, but a fix: I implemented a reboot once a day to fix this. will implement a better fix later, but web.py is still very much work in progress. thanks!
