### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by ahiguero** [DShield-ISC/dshield#121]
when doing the installation it stops with the following error

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pip in ./cowrie-env/lib/python2.7/site-packages (18.0)
2018-09-20_192701 ### Running: pip install --upgrade -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
2018-09-20_192702 ### DEBUG OUTPUT: EXIT CODE NOT ZERO (1)!

**Comment by ahiguero** [comment]
the cause fo the problem is that the cowrie.zip when extracted expands to cowrie-dev-master instead of cowrie-master

**Comment by ahiguero** [comment]
This is the line of code

# step 3 (Checkout the code)
# (we will stay with zip instead of using GIT for the time being)
dlog "downloading and unzipping cowrie"
run "wget -qO $TMPDIR/cowrie.zip https://github.com/micheloosterhof/cowrie/archive/master.zip"
run "unzip -qq -d $TMPDIR $TMPDIR/cowrie.zip "

if [ ${?} -ne 0 ] ; then
   outlog "Something went wrong downloading cowrie, ZIP corrupt."
   exit 9
fi

if [ -d ${COWRIEDIR} ]; then
   dlog "old cowrie installation found, moving"
   # TODO: warn user, backup dl etc.
   run "mv ${COWRIEDIR} ${COWRIEDIR}.${INSTDATE}"
fi
dlog "moving extracted cowrie to ${COWRIEDIR}"
run "mv $TMPDIR/cowrie-**dev**-master ${COWRIEDIR}"

chances are this will change in the future when the maintainer of the code changes the repository so be mindful.

**Comment by ahiguero** [comment]
same result with the "master" getting a lot of python errors when trying to start the cowrie service
Sep 22 10:13:36 raspberrypi systemd[1]: Starting Cowrie SSH and Telnet Honeypot...
Sep 22 10:13:36 raspberrypi cowrie[13451]: Join the Cowrie community at: http://bit.ly/cowrieslack
Sep 22 10:13:36 raspberrypi cowrie[13451]: Using default Python virtual environment "/srv/cowrie/cowrie-env"
Sep 22 10:13:36 raspberrypi cowrie[13451]: Starting cowrie: [twistd   --umask 0022 --pidfile var/run/cowrie.pid --logger cowrie.python.logfile.logger cowrie ]...
Sep 22 10:13:39 raspberrypi cowrie[13451]: Unhandled Error
Sep 22 10:13:39 raspberrypi cowrie[13451]: Traceback (most recent call last):
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 674, in run
Sep 22 10:13:39 raspberrypi cowrie[13451]:     runApp(config)
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
Sep 22 10:13:39 raspberrypi cowrie[13451]:     runner.run()
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 381, in run
Sep 22 10:13:39 raspberrypi cowrie[13451]:     self.application = self.createOrGetApplication()
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
Sep 22 10:13:39 raspberrypi cowrie[13451]:     ser = plg.makeService(self.config.subOptions)
Sep 22 10:13:39 raspberrypi cowrie[13451]: --- <exception caught here> ---
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/src/twisted/plugins/cowrie_plugin.py", line 152, in makeService
Sep 22 10:13:39 raspberrypi cowrie[13451]:     globals(), locals(), ['output']).Output()
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/src/cowrie/output/jsonlog.py", line 52, in __init__
Sep 22 10:13:39 raspberrypi cowrie[13451]:     self.outfile = cowrie.python.logfile.CowrieDailyLogFile(base, dirs, defaultMode=0o664)
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 45, in __init__
Sep 22 10:13:39 raspberrypi cowrie[13451]:     self._openFile()
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 248, in _openFile
Sep 22 10:13:39 raspberrypi cowrie[13451]:     BaseLogFile._openFile(self)
Sep 22 10:13:39 raspberrypi cowrie[13451]:   File "/srv/cowrie/cowrie-env/local/lib/python2.7/site-packages/twisted/python/logfile.py", line 81, in _openFile
Sep 22 10:13:39 raspberrypi cowrie[13451]:     self._file = open(self.path, "wb+", 0)
Sep 22 10:13:39 raspberrypi cowrie[13451]: exceptions.IOError: [Errno 2] No such file or directory: u'log/cowrie.json'

**Comment by jullrich** [comment]
just made a possible fix live. Please try again.

**Comment by ahiguero** [comment]
hello Johanes

Tested the new change it is working now. thanks for the help.
