### ISSUE TITLE
webpy throwing errors in the logs

### ISSUE THREAD

**Issue by ahiguero** [DShield-ISC/dshield#122]
although the service can be restarted, the webpy services continues to throw errors int eh logs whenever there is a hit on port 80 or 8080 

Sep 29 15:38:10 raspberrypi webpy[2069]: Traceback (most recent call last):
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
Sep 29 15:38:10 raspberrypi webpy[2069]:     self.process_request(request, client_address)
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
Sep 29 15:38:10 raspberrypi webpy[2069]:     self.finish_request(request, client_address)
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Sep 29 15:38:10 raspberrypi webpy[2069]:     self.RequestHandlerClass(request, client_address, self)
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
Sep 29 15:38:10 raspberrypi webpy[2069]:     self.handle()
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
Sep 29 15:38:10 raspberrypi webpy[2069]:     self.handle_one_request()
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
Sep 29 15:38:10 raspberrypi webpy[2069]:     method()
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/srv/www/bin/web.py", line 101, in do_GET
Sep 29 15:38:10 raspberrypi webpy[2069]:     targetip = local_pub_IP.json()['ip']
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 896, in json
Sep 29 15:38:10 raspberrypi webpy[2069]:     return complexjson.loads(self.text, **kwargs)
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Sep 29 15:38:10 raspberrypi webpy[2069]:     return _default_decoder.decode(s)
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Sep 29 15:38:10 raspberrypi webpy[2069]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Sep 29 15:38:10 raspberrypi webpy[2069]:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
Sep 29 15:38:10 raspberrypi webpy[2069]:     raise ValueError("No JSON object could be decoded")
Sep 29 15:38:10 raspberrypi webpy[2069]: ValueError: No JSON object could be decoded

**Comment by omnipotence407** [comment]
I threw a debug line in to see what it is trying to decode and here is what it keeps failing to decode:

> <html xmlns="http://www.w3.org/1999/xhtml">
>   <head>
>     <title>SANS Internet Storm Center / DShield</title>
>     
>   </head>
>   <body>
>     <p>This page has moved to a <a href="https://isc.sans.edu/index.html">
>       https://isc.sans.edu/</a>.</p>
>   </body>
> </html>

Not sure exactly which site it is pulling down - but in the "/srv/www/bin/web.py" file there is a call to "https://www4.dshield.org/api/myip?json" to get our public IP.  I cannot curl that site directly due to certificate issues. However, curling to www vice www4 gets me what looks like the correct json file.

Looks like on those calls, it is just getting a "<Response [404]>".  I changed it to www and now local_pub_IP="<Response [200]>".  I'm also not seeing any errors being thrown.  I will let it sit for 24 hours and see what happens.

**Comment by jullrich** [comment]
ah. this is very helpful. I think this is related to some security improvements we made recently to be pickier on hostnames. I should be able to fix that shortly on the server.

**Comment by omnipotence407** [comment]
After making the change to www, I didn't recieve any more JSON errors.  I did get a couple broken pipe errors, but those stopped at 0638 UTC.

@jullrich I'm glad this all helps.  Should I change back to www4?  I see that the response to a curl has changed, although it is still not a JSON.  Now getting "curl: (51) SSL: no alternative certificate subject name matches target host name 'www4.dshield.org'"

**Comment by omnipotence407** [comment]
Since making the change to www from www4, I did not receive any JSON errors.  I did get some broken pipe errors - but the last one was at on 2 October at 0638 UTC.

I am getting a different response when I curl the www4 address, but not the JSON I get from www.  I get "curl: (51) SSL: no alternative certificate subject name matches target host name 'www4.dshield.org'"

I changed it back to www4 and I am still getting the 404 response, but I'm not getting any errors anymore.  I'll check back in a few hours to make sure.

**Comment by omnipotence407** [comment]
The errors are back with www4.  Switching back to www.

**Comment by jullrich** [comment]
The "www4" hostname should work again, and now use a valid TLS certificate

**Comment by mikep11** [comment]
I see the difference on the curl - looks good there.  Made the change and no errors yet.  I will check again tomorrow evening to make sure.

**Comment by ahiguero** [comment]
awesome i will also test today and confirm

**Comment by ahiguero** [comment]
Si far so good. It is working

**Comment by mikep11** [comment]
No more JSON errors, but instead it crashed out due to too many failed connections.

> Traceback (most recent call last):
>   File "/srv/www/bin/web.py", line 42, in <module>
>     local_pub_IP = requests.get('https://www4.dshield.org/api/myip?json', verify = False)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www4.dshield.org', port=443): Max retries exceeded with url: /api/myip?json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5ebcf10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Then:
> systemd[1]: webpy.service: Main process exited, code=exited, status=1/FAILURE
> systemd[1]: webpy.service: Unit entered failed state.
> systemd[1]: webpy.service: Failed with result 'exit-code'.

**Comment by ahiguero** [comment]
> No more JSON errors, but instead it crashed out due to too many failed connections.
> 
> > Traceback (most recent call last):
> > File "/srv/www/bin/web.py", line 42, in 
> > local_pub_IP = requests.get('https://www4.dshield.org/api/myip?json', verify = False)
> > File "/usr/lib/python2.7/dist-packages/requests/api.py", line 70, in get
> > return request('get', url, params=params, **kwargs)
> > File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
> > return session.request(method=method, url=url, **kwargs)
> > File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
> > resp = self.send(prep, **send_kwargs)
> > File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
> > r = adapter.send(request, **kwargs)
> > File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
> > raise ConnectionError(e, request=request)
> > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www4.dshield.org', port=443): Max retries exceeded with url: /api/myip?json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb5ebcf10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> 
> Then:
> 
> > systemd[1]: webpy.service: Main process exited, code=exited, status=1/FAILURE
> > systemd[1]: webpy.service: Unit entered failed state.
> > systemd[1]: webpy.service: Failed with result 'exit-code'.

i can confirm the same

**Comment by jullrich** [comment]
"fixeD" by implementing a daily reboot.
