### ISSUE TITLE
TTY Logging

### ISSUE THREAD

**Issue by mikep11** [DShield-ISC/dshield#123]
TTY Logging is not working based on errors in the cowrie.log and an empty log/tty folder.

Looks like a setting needs to be changed in /srv/cowrie/cowrie.cfg, specifically setting 
`ttylog_path = ${honeypot:log_path}/tty"` 
(matching the setting in /srv/cowrie/etc/cowrie.cfg.dist)  

Alternatively, it can be hard coded "log/tty" to match settings within the same config file.  Either seems to work for me.

Hope this helps!

**Comment by jullrich** [comment]
I "fixed" this by disabling tty logging. currently, tty logging isn't of much use for the honeypot operation but tends to fill up the disk (and wear out the Pi's SD Card). But you should be able to enable it in cowrie.cfg if needed.
