### ISSUE TITLE
404 not updating properly 

### ISSUE THREAD

**Issue by ahiguero** [DShield-ISC/dshield#124]
when i look at my status reports i see this:

Firewall reports: 2019-01-14 14:04:36
ssh/kippo reports: 2019-01-14 14:04:59
404 logs: 2019-01-14 14:04:36

when when i look at my 404.reports page...

Last parsed submission: 2019-01-14 14:04:36 (Submissions are parsed twice an hour).
Total reports today: 0

and this has been going on for a while. i have rebuilt the pi thinking there was something wrong with my setup. are there any other logs that i can check / review to figure is there is something wrong with it?

**Comment by ahiguero** [comment]
yes, and now the reports have been updating after a couple of days. i also saw on their slack channel that they will be doing some changes to it but there is no eta as to when that will happen.

**Comment by Davidy92** [comment]
I've come across the same issue, I noticed that my honeypot just randomly stopped sending out 404 reports for over a month now, I have rebuilt my pi 2 times with the same results. Everything sends through BUT the 404 error. Any recommendations? or is it just a waiting game until they update the git.

**Comment by ahiguero** [comment]
I stopped using the project as it seems that it is not getting the support it needs. It is not like tons of tickets are being opened on a day to day basis. More often than not it is things like this that are only detected when a user reports it.

**Comment by Davidy92** [comment]
@ahiguero did you completely remove honeypots from your environment? or did you find another project for your honeypot needs? If so, could you please share which one you are using so I can look into change.

**Comment by ahiguero** [comment]
I have not had time to look for another project although I have looked at implementing cowrie directly but I have not had time todo that

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jullrich** [comment]
released a new version last week that should fix many of the submission errors but also reboots the honeypot daily to clean up web.py issues.
