### ISSUE TITLE
Last Web Log Received, missing date when running status.sh

### ISSUE THREAD

**Issue by Davidy92** [DShield-ISC/dshield#125]
So the issue i'm having is, when running the following script "sudo /home/pi/install/dshield/bin/status.sh",
I receive the following output 

API Key configuration ok
E-mail : [hidden]  <--- I just wrote this to censor my email
API Key: [hidden] <--- I just wrote this to censor my API-KEY
User-ID: [hidden] <--- I just wrote this to censor my User-ID
**Last Web Log Received:**
Last 404 Log Received: 2019-03-11 14:13:27
Last ssh Log Received: 2019-03-11 13:57:41
Last ssh Firewall Log Received: 2019-03-11 14:13:27
Current Time/Date: 2019-03-11 07:40:01

Notice that i'm receiving new dates for the 404, ssh, firewall logs, everything seems to be constantly flowing to the sans website, but for some reason I can't get a date to show up on the **Last Web Log Received**, 

I've checked my firewall and everything looks correct, I mean if everything else is sending out why wouldn't the web log be sending out it just doesn't make sense, why that's a special case.

Yes, I doubled checked my email & api-key they both are correct, I even decided to print the output of the $status variable within the status.sh script to see what the output is, and I  received the <result>ok</result>, so I know my email and api check out.

Any recommendations would be greatly appreciated, 

I'm using the Raspbian Lite Stretch (as stated in the tutorial), my firewall is configured correctly

Also when I run the following command:
sudo tail -f /var/log/dshield.log

New traffic is constantly being logged.

Can anyone help me out with some suggestions please, this is a fresh install this isn't being upgraded from a previous version of the Dshield project, its all fresh in my Rpi3

**Comment by jullrich** [comment]
closing this as it should be fixed in the last version. Please try again after updating. Thanks for your help!
