### ISSUE TITLE
Web service going absolutely down at times (reboot manually to solve?)

### ISSUE THREAD

**Issue by fzanuzzo** [DShield-ISC/dshield#127]
I've recently setup my honeypot, and my online port monitors sometimes alert me on the Web service going down permanently while the other ones (Telnet and SSH) frequently go down and up quickly by their turns automatically.
Probably, due to heavy attack causing crash of that service? As I said, the others handle OK.
I reboot so to have all working back again...

**Comment by jullrich** [comment]
I automated the reboot (daily) for now. not ideal, but please update and let me know if that helps.

**Comment by fzanuzzo** [comment]
It may have helped, not ideally as you said, but the root cause should be discovered.
Maybe it has to do with DoS, no? If so, a rule in iptables could fix this issue, right?
Recently, I addressed OK an invalid ICMP packet trouble on port 22 that way...
