### ISSUE TITLE
Slack invite is no longer valid

### ISSUE THREAD

**Issue by Prune2000** [DShield-ISC/dshield#129]
Hey!

I would love to participate to the project and discuss a little more about it. Could you make a new invite link in the README please?

**Comment by cherokeejb** [comment]
Hi Prune 2000

You should be able to join the slack community with this:

https://join.slack.com/t/dshieldusers/shared_invite/enQtNTQxMTAyMzUxMjQ4LTM0YTViMjg3NmQ0NDE0YTkzN2MwNjcwMTUwMTQzYTYwYjlhNDY5ZWVjZDgxMjM5ZGQzYjdlZmZlMDUwMzNlZDU

That may only be a one-time or temporary link, so let's leave the
issue open until a moderator can add the permanent, new slack link
here on github, unless that one will continue to work for others



cherokeejb_

**Comment by Prune2000** [comment]
Perfect, thank you!

**Comment by jullrich** [comment]
fixed by pointing the link to https://dshield.org/slack/
