### ISSUE TITLE
Firewall logs not uploading from RPI

### ISSUE THREAD

**Issue by m4g1cm4n** [DShield-ISC/dshield#130]
Hey guys

I'm not seeing Firewall logs uploading from my Pi (fresh setup)

When I try to run the fwlogparser.py script, I get the below

pi@raspberrypi:/srv/dshield $ sudo ./fwlogparser.py
opening /var/log/dshield.log and starting with 1573111921
Traceback (most recent call last):
  File "./fwlogparser.py", line 151, in <module>
    data = (parse(line,logformat,linere))
  File "./fwlogparser.py", line 64, in parse
    logdata['sip'] = d.anontranslateip4(logdata['sip'])
  File "/srv/dshield/DShield.py", line 105, in anontranslateip4
    ip=self.translateip4(ip)
  File "/srv/dshield/DShield.py", line 92, in translateip4
    return self.long2ip4(ip)
  File "/srv/dshield/DShield.py", line 130, in long2ip4
    return socket.inet_ntoa(struct.pack('!I', ip))
struct.error: integer out of range for 'I' format code

If I delete the dshield.log and let it be recreated, I'll get maybe one successful upload then it will stop working again. 

Thanks!

**Comment by jullrich** [comment]
I know we talked on slack about this. is this still happening?

**Comment by m4g1cm4n** [comment]
Hey - wasn't me on slack :)

But, yeah issue still persists. Still haven't seen a firewall update since 07/11

**Comment by jullrich** [comment]
Could you please email me the /var/log/dshield.log file from your system (or upload it to a file sharing site)? ( email: jullrich @ sans.edu ). thanks!

**Comment by jullrich** [comment]
ok. I think I found a (the?) problem. Your log file included null bytes, which can happen if syslog crashes. I am now removing these nulls, and that seems to work. Please do a "git pull" and copy the fwlogparser.py to /srv/dshield . 
BTW: I added a comment with a date to fwlogparser.py to make it easier to check that you got the latest version.

**Comment by m4g1cm4n** [comment]
Same error. Renamed log file, rebooted and still get the error

Current Time 1573595787.0
opening /var/log/dshield.log and starting with 1573585320
Traceback (most recent call last):
  File "./fwlogparser.py", line 177, in <module>
    data = (parse(line,logformat,linere))
  File "./fwlogparser.py", line 71, in parse
    logdata['sip'] = d.anontranslateip4(logdata['sip'])
  File "/srv/dshield/DShield.py", line 105, in anontranslateip4
    ip=self.translateip4(ip)
  File "/srv/dshield/DShield.py", line 92, in translateip4
    return self.long2ip4(ip)
  File "/srv/dshield/DShield.py", line 130, in long2ip4
    return socket.inet_ntoa(struct.pack('!I', ip))
struct.error: integer out of range for 'I' format code

**Comment by jullrich** [comment]
:( make sure you run the latest version of fwlogparser.py . Let me give it another run on my system.

**Comment by m4g1cm4n** [comment]
Yeah - timestamped version

#!/usr/bin/env python

# version 2019-11-12-01

**Comment by jullrich** [comment]
send me your dshield.ini file please. I think that is the one thing I don't have yet to replicate your configuration.

**Comment by jullrich** [comment]
actually based on the error, it looks like your DShield.py is old. I just pushed a new fwlogparser.py and DShield.py . both are now timestamped as a comment. See if that helps. Do a "git pull" in /home/pi/install/dshield first. then a bin/install.sh --update --fast. That should copy the new files into /srv/dshield . if that doesn't work: backup your dshield.ini , run uninstall.sh (and copy /etc/dshield.ini back) followed by a "./install.sh --update"

**Comment by m4g1cm4n** [comment]
Looks better - will leave overnight and try again

**Comment by m4g1cm4n** [comment]
Everything looking good now. Firewall logs have and continue to be uploaded overnight

pi@raspberrypi:/srv/dshield $ sudo ./fwlogparser.py
Current Time 1573633016.0
opening /var/log/dshield.log and starting with 1573632119
Error. -1 not in range
processed 16856 lines total and 285 new lines and ended at 1573633012
new skip value is 1

**Comment by jullrich** [comment]
Thanks a lot for your patience in debugging this!
