### ISSUE TITLE
sqlite3.OperationalError: no such table: requests

### ISSUE THREAD

**Issue by deepcore2** [DShield-ISC/dshield#144]
# cd /srv/dshield; ./weblogsubmit.py
Traceback (most recent call last):
  File "./weblogsubmit.py", line 52, in <module>
    rsx=c.execute("""SELECT date, headers, address, cmd, path, useragent, targetip from requests where date>?""",[starttime]).fetchall()
sqlite3.OperationalError: no such table: requests

**Comment by deepcore2** [comment]
Sorry, hit enter too fast...
I tried several clean installs and the pip freeze fix, but when I run the weblogsubmit.py to just force some output, I get this error...

**Comment by freekdk** [comment]
Most likely the service webpy did not start. Did you get "active" as output of the command "sudo systemctl is-active webpy.service"? If not, make it active!

**Comment by jullrich** [comment]
closing this for now. please reopen if this happens again. Improvements to web.py may have fixed this.
