### ISSUE TITLE
Installation fails on Ubuntu 20.04 LTS with "Error running get-pip2, aborting."

### ISSUE THREAD

**Issue by rcgreenw** [DShield-ISC/dshield#148]
Following the instructions for Ubuntu, the install script fails.
  - It fails with the message "Error running get-pip2, aborting."
  - It seems to download it from the bootstrap location, but then fails to run, possibly because the 'python' command doesn't run python2 on 20.04

**Comment by jullrich** [comment]
could you please try:
```
apt install python2
```

and re-run the install script?

will look into the "python" command.

**Comment by rcgreenw** [comment]
Still doesn't work.  Logs attached.
[install_2020-06-30_202049.log](https://github.com/DShield-ISC/dshield/files/4854245/install_2020-06-30_202049.log)

**Comment by Kixxot** [comment]
I installed it on Ubuntu 20.04 LTS with no issues.  Well, I do have an issue with the web server not working, but the install completed and it is reporting firewall info.

**Comment by rcgreenw** [comment]
Yes, it seems to work for me now.  I went back to the same machine and ran 'sudo dshield/bin/install.sh' again and it worked.
