### ISSUE TITLE
Update "install" fails to carry over admin IP address in iptables config

### ISSUE THREAD

**Issue by uberlance** [DShield-ISC/dshield#150]
As context, my Pi running dshield is connected outside my firewall.  Due to a quirk of my ISP, my Pi sits on a different subnet than my firewall (behind which are my munin monitoring server and the seat I use to administer the Pi).  After the most recent update (which I have set for auto) I could no longer connect over ssh - connection refused.  After reviewing the install log from the night before, I found that while the script had successfully identified the pre-existing dshield.ini and carried it over, the iptables config was overwritten to only allow admin connections from the honeypot's local network.

At this point, I am assuming that the approach of automatically populating both dshield.ini and iptables with the subnet of `honeypotip` was for simplicity.  I see two opportunities for improvement:

1. On initial install, revise the prompt for which IPs/networks should be ignored and/or used for administration to better explain the purpose of the value.  It can still pre-populate with the local subnet to make it easy.
2. When install.sh detects a pre-existing installation, read in the `nohoneyips` value to populate the appropriate iptables entry.  Alternately, we could add a discrete `adminips` line to avoid collision with other uses of `nohoneyips`

If I have time in the next month to tackle this, I will but wanted to get the issue out there in case it could be easily addressed in another merge.  Also, let me know if I should separate these into a "bug" and an "enhancement".

**Comment by jullrich** [comment]
Thanks for reporting this!

**Comment by jullrich** [comment]
should be fixed by my last commit (https://github.com/DShield-ISC/dshield/commit/b7b64d68e3b142c8dfaaf6f7d3c95b5d0f3f15d4) . will leave this open until the fix is verified.
