### ISSUE TITLE
install.sh optimisations 

### ISSUE THREAD

**Issue by tvfischer** [DShield-ISC/dshield#161]
I've been going through the install.sh script to optimise a docker version and have a few suggestions.

the script does an update-rc here:
https://github.com/DShield-ISC/dshield/blob/2fe59c2cb63b4c8d6f5da56e85d786c5c3564a36/bin/install.sh#L1622
is this really required? a few lines above, you delete the `/etc/init.d/cowrie` file so this command fails

Could we change the `wget` commands to `curl`; its more about consistency as the api calls are done with `curl` and some of the downloads are `wget`.
eg
https://github.com/DShield-ISC/dshield/blob/2fe59c2cb63b4c8d6f5da56e85d786c5c3564a36/bin/install.sh#L1438
could be changed to
`run "curl -Ls -o $TMPDIR/cowrie.zip https://www.dshield.org/cowrie.zip"`

**Comment by jullrich** [comment]
working on some updates to the honeypot this morning and will include this issue.

**Comment by jullrich** [comment]
fixed in update going live shortly (version 75)
