### ISSUE TITLE
Can't Remove / Uninstall

### ISSUE THREAD

**Issue by jmb1304** [DShield-ISC/dshield#17]
There is not a uninstall/remove script. How do I uninstall dshield?

**Comment by jullrich** [comment]
The idea is that you install the DShield software on a "blank" install of the Raspian OS. So to uninstall, you just restore the Raspian OS.

Modifications made by the install script:
- obviously you want to delete the 'dshield' directory and sub directory created by git clone
- remove the /etc/dshield.conf file
- uninstall mysql (unless you had it already installed)
- the installer will change the ssh port from 22 to 12222 . you can undo this in /etc/ssh/sshd_config
- remove /etc/rsyslog.d/dshield.conf
- remove /etc/cron.d/dshield
- remove /srv/www/html
- remove /var/log/mini-httpd
- remove /srv/cowrie
- uninstall postfix
