### ISSUE TITLE
iptables path in status.sh

### ISSUE THREAD

**Issue by rcgreenw** [DShield-ISC/dshield#181]
This change added the full path to the call to iptables:
https://github.com/DShield-ISC/dshield/commit/84aaa40ec6fc8341edfc9c8e31735778e1e3c27a

The problem is different versions of Ubuntu have iptables in different places.
18.04.5 LTS (Bionic Beaver) has iptables in /bin
20.04.2 LTS (Focal Fossa) has iptables in /usr/sbin

**Comment by rcgreenw** [comment]
This is the line:
https://github.com/DShield-ISC/dshield/blob/c7e2f44f4b8bca3c5419a55b644c20fd3d2d1301/bin/status.sh#L197

**Comment by jullrich** [comment]
Thanks! fixed.
