### ISSUE TITLE
Process "randomsound"

### ISSUE THREAD

**Issue by Taomyn** [DShield-ISC/dshield#184]
Is the process "randomsound" required by the DShield sensor?

I see it running on my Pi-3 and using CPU and just wondering why it's there as I can't find much information about it.

![image](https://user-images.githubusercontent.com/4365929/112598821-69771e80-8e0f-11eb-8e28-0d5ca4465ee5.png)

**Comment by jullrich** [comment]
The "randomsound" process is used to get more entropy (better random numbers) by including noise from the soundcard. Probably not really needed other than to create the certificates during installation it may be helpful.

**Comment by Taomyn** [comment]
So I can kill it and stop it from running all the time?

**Comment by jullrich** [comment]
yes. no harm in killing it

**Comment by Taomyn** [comment]
Great, thank-you
