### ISSUE TITLE
- Local Reporting( .EDU site) - Logs --> .CSV files for database

### ISSUE THREAD

**Issue by dcj9** [DShield-ISC/dshield#185]
Hello,

Just trying here, maybe someone can yell at me and point me in the right direction
I see in DShield.py where things are stripped, then based upon the API key the information is then grouped or categorized by my user id (or api whatever). I get the logs. I altered the websubmit.py, it updates the logs. However its not broken into a .CSV
- I have the sql database created
- I have the sql server created
- I have the simple http site to upload the data from the Honeypot to my server.
- I am trying to create the .CSV files that dshield.org produces without dshield doing the computations
- 3 HoneyPots initiated, 2 reporting to dshield.org and updating as normal. a 3rd to send values to our database and check or numbers against DSHIELDs to determine which threats may be more relative for us. (My University is University of New Hampshire, north eastern USA)
- Any ideas or advice would be appreciated

**Comment by jullrich** [comment]
I added an optional parameter to dshield.ini . the "localcopy" parameter will be used to log all firewall and weblogs submitted to a local file in addition to submitting it to dshield. The log is created in JSON, not CSV as we use JSON to submit data (and the added ability to encode more complex objects is needed). To log everything to a file called "/tmp/debug.log", add this file to /etc/dshield.ini

localcopy=/tmp/debug.log

(I did not label this a new version yes, so you need to manually do a git pull to get this update)
