### ISSUE TITLE
Status reports "webserver not exposed" when it is

### ISSUE THREAD

**Issue by Taomyn** [DShield-ISC/dshield#187]
Hi, I'm trying to figure out why recently my sensor is reporting that the webserver is not exposed when it is because I can open the web page from an external site.

![image](https://user-images.githubusercontent.com/4365929/129323533-3ba11939-ce0b-4397-9ea3-f68e8887085c.png)

The status reports:

```
###### Checking various files

OK: /var/log/dshield.log
OK: /etc/cron.d/dshield
OK: /etc/dshield.ini
OK: /srv/cowrie/cowrie.cfg
OK: /etc/rsyslog.d/dshield.conf
OK: firewall rules
ERROR: webserver not exposed. check network firewall

```
Everything looks fine except the error. I even tried the check manually and it shows:

```
pi@hibbert:~ $ curl -s 'https://isc.sans.edu/api/portcheck?json'
{"port80":"closed"}

```
I've tried capturing packets on my firewall to see if a rule is blocking the connection but I cannot find it.

Can you tell me what IPs to expect the check to come from so I can look for any connections from them, or any other clues what to find in the captures?

**Comment by Xusqui** [comment]
Same here...

I don't know exactly how it works, but it fails to get the external IP address, so I changed manually in /etc/dshield.ini the external IP address. Anyway it always says webserver not exposed when it is properly exposed in the router

**Comment by skraynick** [comment]
I have the same issue, but my pi is definitely exposed. I am getting hits and it is updating in my dashboard. I ran an external port scan and all is okay... so seems more like an error when the error is displayed. 
![issue](https://user-images.githubusercontent.com/3478646/132159147-5723a542-f3a7-41c8-8b2d-c766f7a333ce.png)

**Comment by jullrich** [comment]
Sorry, but after a data center move, the outbound connections to test the honeypots failed. This should be fixed now.

**Comment by Taomyn** [comment]
> Sorry, but after a data center move, the outbound connections to test the honeypots failed. This should be fixed now.

Thanks, confirmed working again
