### ISSUE TITLE
Reran installation and added additional trusted IP's and only the original is working

### ISSUE THREAD

**Issue by robertstrom** [DShield-ISC/dshield#189]
Hello,

I recently updated the DShield Honeypot and updated the trusted IP addresses (added two additional trusted IP addresses via the installation script) and I am unable to connect from either of the two new trusted IP addresses.

I am still able to connect from the original trusted IP address, just not either of the two new ones.

The Honeypot is setup as a VM in the Digital Ocean cloud. The other two trusted IP addresses are also both Digital Ocean VM's. The other two Digital Ocean VM's allow all outbound ports.

I am seeing all three IP addresses listed in the IPTABLE rules in /etc/network/iptables

-A INPUT -i eth0 -s 72.2xxx.xx.xx -p tcp --dport 12222 -j ACCEPT
-A INPUT -i eth0 -s 157.2xx.xxx.xxx -p tcp --dport 12222 -j ACCEPT
-A INPUT -i eth0 -s 157.2xx.xxx.xx -p tcp --dport 12222 -j ACCEPT

I am using the same command line to logon from all three machines

ssh -p 12222 rxxxx@167.xx.x.xxx

Yet I can only logon from the original IP address that was entered as trusted, my home IP address.

Any thoughts on what the issue is?

Thanks

**Comment by jullrich** [comment]
are you not able to connect at all or do you get authentication failure messages?

**Comment by freekdk** [comment]
You may try to debug using tcpdump on your honeypot and see if packets are coming in from the IP address you try to connect from. If not the problem is outside your honeypot.
Command:
`tcpdump -i <interface> -c 10 <from-ip-address>`
dumps max 10 packets from that ip adress.

**Comment by paulwratt** [comment]
if your 72 is the one that is working, then it appears you 152 are blocked somewhere, you could try something like:
```
ip route show | grep / | grep " 152\."
```
if it shows anything, well then you'll know, but if nothing, drop the last grep and see whats there

**Comment by jullrich** [comment]
sorry, not able to reproduce this issue.
