### ISSUE TITLE
/srv/cowrie/log

### ISSUE THREAD

**Issue by jay9883bea** [DShield-ISC/dshield#19]
I've been having problems with my Pi stopping reporting or crashing completely. I tracked this down to a memory problem - specifically, running out of inodes (all 944704 inodes used in /dev/root). It is a 16Gb sdcard.

Once it had got to this stage, it was difficult to track down because of out of memory messages, but running **ncdu** allowed me to identify that the cause was /srv/cowrie/log, which was filled with hundreds of thousands of documents like **cowrie.json.2016_3_16.1.gz.4.gz.1.gz.5.gz.1.1.5.gz.1.1.1.1.1.1.1.1**

I don't know whether this is a bug, a problem with the original installation, or a logrotate issue. Once the directory has finally been emptied, I will monitor it to see whether the problem reoccurs, or whether it was a one-off.

**Comment by jullrich** [comment]
thanks. this should be fixed in the next update. It is a bug in the log rotate script. 
(I hope to push this out mid next week)
