### ISSUE TITLE
disable the remote access prompts during install

### ISSUE THREAD

**Issue by killamjr** [DShield-ISC/dshield#192]
My honeypot just runs on Linode, and i just manage/update it from the local linode lish console could there be an option to not even bother with the "authorized" remote users?

**Comment by freekdk** [comment]
It is quite unclear what you are asking for. Please elaborate quite extensive what you want?

**Comment by killamjr** [comment]
i host my dshield sensor on linode, as part of the setup process it asks for authorized remote users and uses the ip subnet mask range to allow authorized users presumably on a the same home network.

For a instance hosted on a cloud server, such as mine this option is completely unnecessary, since i can just remote in using their command line console in the cloud server instance, which treats my access as a local login.

**Comment by killamjr** [comment]
example from running the install script:

![image](https://user-images.githubusercontent.com/946258/148652951-6d912d59-552c-4fca-9b91-823546bd0085.png)

in my use case i would prefer not to allow anything from this IP range

**Comment by cherokeejb** [comment]
Hi @killamjr - this part of the install.sh is adding ports and IPs to the iptables (by default in interactive mode, so that no one locks themselves out of accessing the honeypot typically with ssh). 

By default you'll need to go back after the setup and remove or comment out lines you don't need from the iptables.

Maybe also It's a good feature request idea for a PR: to choose at some point in install.sh "advanced - local access only" (I don't think that currently exists?).

**Comment by freekdk** [comment]
@killamjr So, if I understand correctly, you access the honeypot via a tty interface and you do not need the ssh access. It is quite easy to disable the sshd service, "systemctl disable sshd.service", to prevent access via the 12222 ssh port. Cowrie in the honeypot controls the ssh and telnet ports, which has nothing to do with the sshd.service.
Recently I added a feature to have a bash script /root/bin/postinstall.sh with execution rights, which will be executed at the end of the install.sh script. It is meant to adapt the standard installation to your needs in case you do an (automatic) update. So you can add the above command in that script and also do a delayed reboot, which is recommended after an update. In case you want that script somewhere else, you can have a symbolic link in /root/bin pointing to the location of that other script. In my view your request is not general enough to put it in the install.sh script.

**Comment by killamjr** [comment]
> @killamjr So, if I understand correctly, you access the honeypot via a tty interface and you do not need the ssh access. It is quite easy to disable the sshd service, "systemctl disable sshd.service", to prevent access via the 12222 ssh port. Cowrie in the honeypot controls the ssh and telnet ports, which has nothing to do with the sshd.service. Recently I added a feature to have a bash script /root/bin/postinstall.sh with execution rights, which will be executed at the end of the install.sh script. It is meant to adapt the standard installation to your needs in case you do an (automatic) update. So you can add the above command in that script and also do a delayed reboot, which is recommended after an update. In case you want that script somewhere else, you can have a symbolic link in /root/bin pointing to the location of that other script. In my view your request is not general enough to put it in the install.sh script.

thanks, i think i like this option, and i'll probably go this route. I put the issue here thinking maybe it could be a "feature request" that could be ignored if i'm the only one, but i figured i might not be the only person who hosts their dshield instance on cloud server.

**Comment by jullrich** [comment]
closing this. I think @freekdk 's solution "fixes" this more easily.
