### ISSUE TITLE
Install fails due to changed path in downloaded cowrie.zip

### ISSUE THREAD

**Issue by thnilsen** [DShield-ISC/dshield#194]
Just tested the current code on a fresh install of Ubuntu 20.04.

The install.sh script fails after line 1805 as the downloaded https://www.dshield.org/cowrie.zip file when unzipped is stored as .../cowrie-master/ while the script expects ../cowrie/

**Comment by freekdk** [comment]
The change about cowrie-master to cowrie in install.sh should be made undone and after the mv to ${COWRIEDIR}, cowrie-master should be renamed to cowrie. See comment on that change.

**Comment by jullrich** [comment]
fixed by updating the zip file.
