### ISSUE TITLE
Logging filling message/kern.log/dshield.log

### ISSUE THREAD

**Issue by rydogg1** [DShield-ISC/dshield#2]
Kernel messages are filling all three logs.  Not sure if this needs to be considered since most rPI's have limited space.  Is there any sort of clean up or consideration of these messages just going to the dshield.log?

**Comment by jullrich** [comment]
I am planning to have logrotate take care of this. The firewall logs go to dshield.log in order to simplify log rotation for submission so logs are not submitted twice (and only "INPUT" logs go to dshield.log).

**Comment by jullrich** [comment]
actually decided on deleting the dshield.log file after processing it. since the logs are retained in messages and kernel. Not sure if I should remove the duplication between messages and kernel as this is the standard debian configuration and I want to mess with that as little as possible.
