### ISSUE TITLE
DShield report emails say I did not submit any reports

### ISSUE THREAD

**Issue by Taomyn** [DShield-ISC/dshield#226]
Since around 24th March I keep getting the report emails telling me that I did not submit any reports.

I've run the status report and it comes back all green:

![image](https://user-images.githubusercontent.com/4365929/161020986-cbe0ddc0-b2c7-4f04-8634-3e3673ce1d48.png)

I check the log on my Pi and that seems to be logging correctly, even some remote tests to be sure my firewall is diverting the traffic correctly:

![image](https://user-images.githubusercontent.com/4365929/161021831-4230ece8-d294-4062-b18f-ea856c5f55d3.png)

![image](https://user-images.githubusercontent.com/4365929/161021903-fcd82ee1-2c53-4dd4-8330-3d67253fcd24.png)

Any idea why?

**Comment by mitrules** [comment]
Same issue, nothing since 2022/03/24

**Comment by jullrich** [comment]
working on this. The parser is behind due to a bug in a cleanup script. fixing this right now and will close once the parser has caught up.

**Comment by Taomyn** [comment]
I think it's back working again

![image](https://user-images.githubusercontent.com/4365929/161230309-579fabf1-c2f9-423e-a12a-53cc6bfbd9b8.png)

**Comment by jullrich** [comment]
backlog is cleared and processing is working again. Added additional checks to monitor the backlog.
