### ISSUE TITLE
Clean install on raspbian lite fails to start isc-agent at reboot

### ISSUE THREAD

**Issue by dbtick** [DShield-ISC/dshield#248]
Clean raspbian lite build, on a raspberry pi 2B (yep!) -  ignoring errors in installation logs for now, installation appears to complete. On reboot isc-agent.service shows as failed

root@orac:/srv# systemctl --all | grep failed
● isc-agent.service              loaded    failed   failed    ISC Agent Web Honeypot

Quick look at journal, 
root@orac:/srv# journalctl -u isc-agent
...
Jan 27 20:28:29 orac systemd[527]: isc-agent.service: Failed to locate executable /srv/isc-agent/bin/isc-agent: Permission denied
Jan 27 20:28:29 orac systemd[527]: isc-agent.service: Failed at step EXEC spawning /srv/isc-agent/bin/isc-agent: Permission denied
...

A quick look at isc-agent, missing execute bits...

root@orac:/srv# ls -l /srv/isc-agent/bin/
total 4
-rw-r--r-- 1 root root 929 Jan 27 20:17 isc-agent

However, when this is fixed, it still fails to start /srv/log/isc-agent.err shows:
`Traceback (most recent call last):
  File "/srv/isc-agent/./main.py", line 4, in <module>
    from twisted.internet import reactor
ModuleNotFoundError: No module named 'twisted'`

fix this, then sqlalchemy missing.... Was this checked on a clean build, or have I _really_ missed something obvious?
[install_2023-01-27_200905.log](https://github.com/DShield-ISC/dshield/files/10523058/install_2023-01-27_200905.log)

**Comment by deekayen** [comment]
I'm having the same issue on my 2B. I re-ran the installer, then `sqlalchemy` was the missing module. I re-ran it again, then it was `twisted` again. I re-installed Raspbian wondering if maybe I just had laggy Internet on the first round, but I'm back to the missing `twisted` module.

```
root@dshield-honeypot:/srv/log# tail isc-agent.err
Traceback (most recent call last):
  File "/srv/isc-agent/./main.py", line 4, in <module>
    from twisted.internet import reactor
ModuleNotFoundError: No module named 'twisted'
```

The server doesn't really complain about this problem at all. The status.sh script shows everything is OK. I only really found the problem because I thought port 8000 or something like it was supposed to be listening, but wasn't when I checked `netstat` on reboot.
```
OK: /var/log/dshield.log
OK: /etc/cron.d/dshield
OK: /etc/dshield.ini
OK: /srv/cowrie/cowrie.cfg
OK: /etc/rsyslog.d/dshield.conf
OK: nf-firewall rules
OK: webserver exposed
```
The Pi is still reporting telnet/SSH. I haven't crawled through the install script deep enough to try doing the twisted install manually in the correct venv.

**Comment by deekayen** [comment]
I re-ran the install from a fresh pull today and still don't see anything web-specific listening:

```
root@dshield-honeypot:/srv/log# netstat -an | grep tcp
tcp        0      0 0.0.0.0:12222           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:2223            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN
```

The `isc-agent.err` log still complains about missing `twisted`.

**Comment by deekayen** [comment]
Rolling back to e79af9578399066b5a38713c7f85029e360b7350 fixed it - by that I mean port 8000 is listening again.

```
pi@dshield-honeypot:~ $ netstat -an | grep tcp
tcp        0      0 0.0.0.0:2223            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:12222           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN
```

**Comment by port0x50** [comment]
This should be fixed now.

**Comment by dbtick** [comment]
Yes, updated to latest, now have both cowrie and web honeypots running with current - thanks!

**Comment by deekayen** [comment]
It's just telling me my RPi2 isn't supported now.

```
pi@dshield-honeypot:~/dshield $ git pull origin master
pi@dshield-honeypot:~/dshield $ git checkout master
pi@dshield-honeypot:~/dshield $ sudo bin/install.sh --update
#############################################################################
Log /srv/log/install_2023-04-19_134514.log started.
ATTENTION: the log file contains sensitive information (e.g. passwords, API keys, ...)
           Handle with care. Sanitize before submitting.
Checking Pre-Requisits
You are not running a supported operating systems. Right now, this script only works for Raspbian and Ubuntu 18.04/20.04 with experimental support for Amazon AMI Linux.
Please ask info@dshield.org for help to add support for your flavor of Linux. Include the /etc/os-release file.
pi@dshield-honeypot:~/dshield $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
pi@dshield-honeypot:~/dshield $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
