### ISSUE TITLE
Installation not creating pid/run folder

### ISSUE THREAD

**Issue by dbtick** [DShield-ISC/dshield#249]
Clean build - installed on clean raspbian - latest as of Jan 2023 on RPi 2B. (other issues "fixed" to get this far)

after install - isc-agent startup takes a long time, investigation into logs - systemd complaint:

systemd[1]: isc-agent.service: Can't open PID file /srv/isc-agent/run/isc-agent.pid (yet?) after start: Operation not permitted

looks like the installer is not creating a pid folder - /srv/isc-agent/run

create this manually and the startup completes quickly. (systemctl start isc-agent).

However web.py fails, 

INFO :: 2023-01-27 20:52:25,250 :: <PID 1782:MainProcess> :: __main__ :: L:20 :: Plugin tcp:http not found

**Comment by port0x50** [comment]
It looks like the pid folder is being created now. Additionally, the L:20 is probably resolved now as well.

**Comment by dbtick** [comment]
Fixed and closed - thanks!
