### ISSUE TITLE
Missing web.py service

### ISSUE THREAD

**Issue by AFOSDTU** [DShield-ISC/dshield#264]
One of the cronjobs calls weblogsubmit.py. The weblogsubmit does a "systemctl restart webpy" and so does the webpy.sh also part of the cron job.

BUT: I can't find any traces in the install.sh script of a webpy service being defined under systemd, and as a consequence the bi-hourly cronjob fails with "Failed to start webpy.service: Unit webpy.service not found."

I must admit that I improvised a bit during install, first of all using Debian 11.6 as underlying OS instead, but I can't see how I could have caused a this.

**Comment by port0x50** [comment]
It has been replaced with the isc-agent.service, that said, I've noticed it in /etc/cron.d/dshield as well. For the time being, I have the webpy.sh line commented out as well as the reboot. It was my understanding that the reboot was in place due stability with the webpy.service as well.

I believe these are generated in the install.sh, so it may be worth revising to remove those lines pending further discussion.

user@user:/srv/db $ cat /etc/cron.d/dshield
#22,52 * * * * root cd /srv/dshield; ./weblogsubmit.py ; sleep 10; ./webpy.sh
22,52 * * * * root /srv/dshield/fwlogparser.py
51 7 * * * root cd /home/user/dshield/bin/.; ./update.sh --cron >/dev/null
#31 5 * * * root /sbin/reboot
26 5 * * * root cd /srv/dshield; ./status.sh >/dev/null

**Comment by jullrich** [comment]
removed the old cron jobs. web.py is no longer used, instead we now have isc-agent.
