### ISSUE TITLE
log submission

### ISSUE THREAD

**Issue by S-K104** [DShield-ISC/dshield#267]
hi just looking for any suggestions to get log submission working for the honeypot on Ubuntu  . 

Setup completed successfully and all looks ok see status in screenshot below.

When I look at my account on the ISC it just says "we have not received any logs from you today"

My linux is very basic so any help on what to do would be appreciated! 
I have tried a reinstall but still the same.

![image](https://github.com/DShield-ISC/dshield/assets/129976961/b31b9ae1-7c8e-4c9b-8fd6-6df69098efb6)

**Comment by jullrich** [comment]
could you please email me your userid so I can check the server end? thx (jullrich - at - sans . edu )

**Comment by S-K104** [comment]
Sure... its 3000044530

**Comment by S-K104** [comment]
hello did you get my email with our userid? did you find anything at the server end?
thanks
