### ISSUE TITLE
Error install.sh --update

### ISSUE THREAD

**Issue by newwhitebear** [DShield-ISC/dshield#269]
Good evening,
I am submitting the log obtained after the attempt to update the honeypot system and the isc-agent error file.
I am the user User ID #: 3000022252 - Gian Paolo Marcolongo.
My system was down from May 10th to May 28th because I didn't have an ADSL connection. Upon recovery I ran git pull to update the system, as I had checked on the second system I use on a mobile line. Then I ran sudo /dshield/bin/install.sh --update as per the manual but the process crashed due to a dependency error. Run on the other system everything went smoothly.
I use a 32bit raspbion os - bullseye (the other is 64bit).
I await your clarifications.
Thank you
[install_2023-05-29_161923.log](https://github.com/DShield-ISC/dshield/files/11604440/install_2023-05-29_161923.log)
[isc-agent.err.log](https://github.com/DShield-ISC/dshield/files/11604493/isc-agent.err.log)

**Comment by DeemOnSecurity** [comment]
A bit of an odd issue. `isc-agent.err.log` indicates there is a DNS issue preventing callback and the install log indicates there's a null byte in `pip._internal.utils.misc.ensure_dir`. Have you tried installing this again since initially reporting this bug?

**Comment by newwhitebear** [comment]
No. I didn't try to run install.sh --update after the report, because cowrie reported an error: missing cowrie.log, which I manually added empty. The weird thing is that ssh log is always empty and honeypot.log sometimes. It would not mean anything but before there was always something. I think I've seen a few times that cowrie gave error in the starting phase.
Before trying again install.sh I was waiting for your answer. The raspbian os is 32bit. The 64bit one has never created any problems.
Should I try again?

**Comment by DeemOnSecurity** [comment]
If you don't mind! I checked the code base for null bytes just to be safe and came up empty

**Comment by newwhitebear** [comment]
Okay. I'll try running install.sh again tonight

**Comment by newwhitebear** [comment]
Last night I tried running install.sh --update again but the result didn't change. The procedure was aborted with an error message and left cowrie not installed or the installation was not completed. The cowrie.cfg configuration file has been deleted. On reboot cowrie startup for ssh and telnet failed due to missing configuration file. The next step is to redo the microdrive from scratch as a new install. But I need time to make it. If I run the setup.py present in the cowrie directory, does it cause any problems?
add log file
[install_2023-06-10_230514.log](https://github.com/DShield-ISC/dshield/files/11715690/install_2023-06-10_230514.log)
[isc-agent.err.log](https://github.com/DShield-ISC/dshield/files/11715691/isc-agent.err.log)

**Comment by jullrich** [comment]
try a "git pull" in the install directory and another install.sh --update . See if it completes now.

**Comment by newwhitebear** [comment]
Operation already attempted several times. In the end I chose to start from scratch with a 64bit raspbian OS, which currently works.
