### ISSUE TITLE
AWS Install Instructions: may need update regarding public IP address

### ISSUE THREAD

**Issue by cqueern** [DShield-ISC/dshield#270]
It’s been a while since I tinkered here so forgive me if this is wrong, but I believe the [AWS install instructions](https://github.com/DShield-ISC/dshield/blob/main/docs/install-instructions/AWS.md) are not accurate. I think after launching the instance in Step 9, one must go to Elastic IP addresses and both allocate and associate a public IP address to the newly created instance, which is super quick. No public IP is automatically granted.

cc: @MHeezy @parthdmaniar

**Comment by parthdmaniar** [comment]
Let me check this.

Thank you.
