### ISSUE TITLE
Clean install on raspbian lite fails to start isc-agent at reboot

### ISSUE THREAD

**Issue by garthoid** [DShield-ISC/dshield#271]
This is virtually the same as [248](https://github.com/DShield-ISC/dshield/issues/248 ) however on a new RPI 4b with a fresh raspian.

I am seeing the exact same issues as 248 and several attempts at reinstall, reboot, fresh pull do not seem to resolve the issue.

248 talked about reverting to an older version but I want to check if I am not missing something else.

`Traceback (most recent call last):
  File "/srv/isc-agent/./isc-agent.py", line 5, in <module>
    from twisted.internet import reactor
ModuleNotFoundError: No module named 'twisted'`

**Comment by garthoid** [comment]
I noticed a fairly recent related change: https://github.com/DShield-ISC/dshield/commit/511644cb3d77b94ccd1610fa10398ce1f3f60aa3

In that: 
`SCAGENTENV="/srv/isc-agent/virtenv"
run "virtualenv --python=python3 $ISCAGENTENV"
run "pip3 install --ignore-installed -r requirements.txt --prefix $ISCAGENTENV"`

When attempting to duplicated this command manually with the same virtualenv I notice the following:
`Ignoring twisted-iocpsupport: markers 'python_full_version >= "3.7.1" and python_full_version < "4.0.0" and platform_system == "Windows"' don't match your environment`

Unless there are some suggestions I am going to try reverting to an older version.

**Comment by garthoid** [comment]
Despite starting over with clean rpi install (bullseye) and following the video instructions isc-agent does not start for same reasons. I can only conclude that the current version is broken.

The install logs also indicate:
`WARNING: twisted 22.10.0 does not provide the extra 'all-non-platform'
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml): started
  Building wheel for cryptography (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1`

I

**Comment by AliceGrey** [comment]
The cryptography library now requires a rust version that is newer than in the raspbian repos (>=1.56.0). I noticed that the cryptography python package is also misidentifying 32-bit raspbian as 64-bit.

```
 Python: 3.9.2
          platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
          pip: n/a
          setuptools: 68.0.0
          setuptools_rust: 1.6.0
          rustc: n/a

```

I was able to manually install the cryptography library after installing rust manually with rustup.

**Comment by malwaredevil** [comment]
> This is virtually the same as [248](https://github.com/DShield-ISC/dshield/issues/248) however on a new RPI 4b with a fresh raspian.
> 
> I am seeing the exact same issues as 248 and several attempts at reinstall, reboot, fresh pull do not seem to resolve the issue.
> 
> 248 talked about reverting to an older version but I want to check if I am not missing something else.
> 
> `Traceback (most recent call last): File "/srv/isc-agent/./isc-agent.py", line 5, in <module> from twisted.internet import reactor ModuleNotFoundError: No module named 'twisted'`

Having this exact error. Checked the isc error file and got the same error. Is there a fix on the way for the script or a step by step on how to fix this?

**Comment by Bill-Thorsteinson** [comment]
I was able to get the isc-agent to build using the commands as root:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source ~/.cargo/env
bin/install.sh --update
```
I don't know if the second line is needed.  isc-agent was not stared by the build so restarted it manually.

`systemctl start isc-agent`

**Comment by m4st3rCh13f3r** [comment]
For what it's worth, here's how I got the honeypot up & running after I received the same errors with isc-agent on an Ubuntu VM:

1. Switch to root user (sudo su -)
2. Upgrade base OS (do-release-upgrade) to upgrade from Ubuntu 20.04 to 22.04.
3. install rust via apt package manager
4. clone & install dshield

These steps allowed the cryptography wheel to build (where it would fail before the OS upgrade), all status checks to pass, and all logs able to be sent to ISC.

**Comment by jslagrew** [comment]
Just did a fresh install using the following guide and things appeared to be working. 

https://isc.sans.edu/honeypotinstall.pdf

This was using the 64-bit Lite installer. After base install, used the following process:

`sudo apt-get update; sudo apt-get full-upgrade -y
sudo apt-get install git -y
git clone https://github.com/DShield-ISC/dshield.git
sudo dshield/bin/install.sh`

Anyone able to confirm their own Raspbian install? I'm going to try 32-bit Lite as well.

**Comment by jullrich** [comment]
please try (in the install directory):
```
sudo git pull
sudo ./bin/install.sh --upgrade
```
