### ISSUE TITLE
weblogsubmit.py fails to connect to database

### ISSUE THREAD

**Issue by Bill-Thorsteinson** [DShield-ISC/dshield#274]
Several times a day `weblogsubmit.py` would report a failure connecting to the database.   I have patched locally to wait up to 10.5 seconds for a connection.  (10 seconds helps, but failures still occur several times a week.)  Patched as follows.

```
--- a/srv/dshield/weblogsubmit.py
+++ b/srv/dshield/weblogsubmit.py
@@ -30,7 +30,7 @@ f.close()

 config = '..' + os.path.sep + 'www'+os.path.sep+'DB' + os.path.sep + 'webserver.sqlite'
 try :
-    conn = sqlite3.connect(config, 10.5)
+    conn = sqlite3.connect(config)
     c = conn.cursor()
     c.execute('''CREATE TABLE IF NOT EXISTS submissions
             (

```

**Comment by jullrich** [comment]
thanks. change made and will be committed shortly.
