### ISSUE TITLE
Installation broken on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by thnilsen** [DShield-ISC/dshield#275]
The current git main version (93) does no longer install correctly on on Ubuntu 20.04 LTS with the latest updates.
Installation tested using 20.04.6 ISO image.

One of the issues is that the isc-agent fails to start due to problems with the Python3 Twisted library. The error reported in /srv/log/isc-agent.err is :

`Traceback (most recent call last):
  File "./isc-agent.py", line 5, in <module>
    from twisted.internet import reactor
ModuleNotFoundError: No module named 'twisted'
`
Output from ./status.sh: 
[status.txt](https://github.com/DShield-ISC/dshield/files/12062934/status.txt)

[dshield.ini.txt](https://github.com/DShield-ISC/dshield/files/12062926/dshield.ini.txt)

[install_2023-07-15_194744.log](https://github.com/DShield-ISC/dshield/files/12062927/install_2023-07-15_194744.log)

The web module does not get installed.

The current version will run partially on Ubuntu 22.04, in that all installed modules starts up as expected, but the web module still fails to install. It also seems to fail to send SSH/Telnet logs, while firewall logs gets submitted.

**Comment by jullrich** [comment]
Please run 
```
sudo git pull
./bin/insta..sh --upgrade
```

I just commited some chances that may fix this issue. 

if this doesn't work: please comment with the output of 
python -V
and 
python3 -V

**Comment by thnilsen** [comment]
@jullrich Thanks for the quick update! The changes resolved the issues with isc-agent and all services are now starting. 

However, the SSH and Telnet logs are still not being uploaded.

###### Are My Reports Received? ######
....
Last 404/Web Logs Received: 2023-07-18 06:15:33
Last SSH/Telnet Log Received: 2022-05-03 00:48:13
Last Firewall Log Received: 2023-07-18 08:00:54

###### Are the submit scripts running?

Last Firewall Log Processed: 2023-07-18 07:45:24
All Logs are processed. You are not sending too many logs
...

Output from
python -V : _Command 'python' not found_
python3 -V: _Python 3.8.10_

**Comment by jullrich** [comment]
fixed with a server side fix.
