### ISSUE TITLE
Minor issue, after update 94, status check script show warnings about "find"

### ISSUE THREAD

**Issue by Taomyn** [DShield-ISC/dshield#283]
Just updated my RPI4 from 93 to 94 and now when I run the status check script I see right at the top:

```
pi@hibbert:~ $ sudo /home/pi/dshield/bin/status.sh
find: paths must precede expression: `type'
find: paths must precede expression: `type'
find: paths must precede expression: `type'


#########
###
### DShield Sensor Configuration and Status Summary
###
#########

Current Time/Date: 2023-09-22 10:10:37
API Key configuration ok
Your software is up to date.
Honeypot Version: 94
```

Everything else seems fine, just wanted to log the issue.

**Comment by jullrich** [comment]
fixing this right now. To update this on your honeypot: Run "sudo git pull" in the shield install directory and copy status.sh to /srv/dshield. Thanks for reporting this.
