### ISSUE TITLE
mini-httpd.conf configures alternate log location for mini-httpd.log

### ISSUE THREAD

**Issue by BrianWGray** [DShield-ISC/dshield#3]
install.sh creates /var/log/mini-httpd but mini-httpd attempts to write to non-existant /srv/www/var/log/

install.sh
#
# creating srv directories
#

mkdir -p /srv/www/html
mkdir -p /var/log/mini-httpd
chmod 1777 /var/log/mini-httpd

---

mini-httpd.conf

logfile=/srv/www/var/log/mini-httpd.log

**Comment by jullrich** [comment]
fixed. (initial idea was to chroot mini-httpd, but that didn't work as I need perl for the little cgi script)
