### ISSUE TITLE
install error when adding cowrie user

### ISSUE THREAD

**Issue by jullrich** [DShield-ISC/dshield#35]
Added user cowrie
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
bin/install.sh: line 496: [: -eq: unary operator expected
Enter password:

**Comment by jullrich** [comment]
likely due to empty mysql password. investigating

**Comment by gebhard73** [comment]
Pull Request #38 should add better error handling, e.g. finding the MySQL root password.

**Comment by gebhard73** [comment]
has this being fixed with some intermediate update? if not pls state the concrete error, thanks

**Comment by jullrich** [comment]
seems fixed now. closing it.
