### ISSUE TITLE
install.sh script fails if dshield is not cloned into user directory 

### ISSUE THREAD

**Issue by BrianWGray** [DShield-ISC/dshield#4]
My original installation attempt was to clone dshield into /opt/sans/dshield this failed as the installation script apparently makes an assumption that the installation is within the user's home directory. I have not narrowed the issue down to the exact source of the issue.

**Comment by jullrich** [comment]
I just ran it like you described, and it worked for me:
```bash
sudo mkdir -p /opt/sans/dshield
sudo chmod 1777 /opt/sans/dshield
cd /opt/sans/dshield/
git clone https://github.com/DShield-ISC/dshield.git
sudo dshield/bin/install.sh
```

closing this issue for now, but please feel free to open again if you can reproduce.

At the beginning of install.sh, the script attempts to figure out the directory it is running in, and all paths are then written relative to this "progdir"
```bash
progname=$0;
progdir=`dirname $0`;
progdir=$PWD/$progdir;
cd $progdir
```
