### ISSUE TITLE
After git pull/install.sh, no firewall reports... (8-May-2017)

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#42]
After doing the 

git pull
sudo bin/install.sh

reboot

I noticed that my firewall/ssh logs stopped updating.
```
pi@TRP2HP:~/dshield $ sudo bin/status.sh
API Key configuration ok
...
Last Web Log Received:
Last 404 Log Received:
Last ssh Log Received: 2017-05-08 15:45:31
Last ssh Firewall Log Received: 2017-05-08 16:40:03
Current Time/Date: 2017-05-08 16:44:11
```

I found that 
```
pi@TRP2HP:~/dshield/bin $ sudo /srv/dshield/pifwparser.py
Traceback (most recent call last):
  File "/srv/dshield/pifwparser.py", line 11, in <module>
    from DShield import DshieldSubmit
ImportError: No module named DShield
```
is likely the cause.  The prior version ran dshield.pl instead.

pi@TRP2HP:~/dshield $ more /etc/cron.d/dshield
10,40 * * * * root /srv/dshield/pifwparser.py

I changed the /etc/cron.d/dshield to run /srv/dshield/dshield.pl instead, and my submissions are going through again.

Looks like the Python module 'DShield' is missing from the current distribution.

**Comment by jullrich** [comment]
Thanks! Working on this... The DShield module is not in the right path it seems. I need to change the configuration file as well. (some work I did this weekend). The idea of "DShield.py" is to combine all the different reports in one submission mechanism (JSON encoded upload via HTTPS) to streamline things on the backend.

**Comment by jullrich** [comment]
the new config file uses the "standard" .ini format, so it can be parsed with respective libraries from bash, python, php, perl. 

sample:
```
[DShield]
userid=11111
apikey=someapikey
logfile=/var/log/kern.log
includefilter=prenatlog
localnet=10.1.1.0/24
mysqlpassword=somepassword
mysqluser=root
version=0.3
```
It should be mostly compatible in that older versions can read it as they will ignore the [DShield] section. In the future, we may introduce additional sections.

**Comment by gebhard73** [comment]
pull request #44 should provide a workaround

**Comment by gebhard73** [comment]
anybody being able to verify that this works now?

**Comment by ktrue** [comment]
I'll give it a try when #44 is pulled into the master :)

**Comment by gebhard73** [comment]
has this also being fixed by the recent updates? if yes, pls close, if no, pls state the remaining issues, thanks
