### ISSUE TITLE
Current Cowrie Version not working anymore

### ISSUE THREAD

**Issue by gebhard73** [DShield-ISC/dshield#43]
Current cowrie version doesn't work anymore, the installation procedure has to be revised in several points.

**Comment by gebhard73** [comment]
should be fixed with pull request #45

**Comment by gebhard73** [comment]
anybody being able to verify that this works now?

**Comment by ktrue** [comment]
I'll give it a try when #45 is merged into the master...

**Comment by jullrich** [comment]
I jsut ran into another "cowrie" problem. The current install scrip assume that there is a /srv/cowrie/start.sh and stop.sh. This is no longer true. Instead, there is now a more init like script: /srv/cowrie/bin/cowrie. But it has to be run as "cowrie", not as root. Also, cowrie now requires a virtual environment (so far, this was an option). I am making some changes to install.sh to hopefully make this work.

**Comment by gebhard73** [comment]
this should all be covered with my pull requests 

----- Originale Nachricht -----
Von: Johannes Ullrich <notifications@github.com>
Gesendet: 30.05.17 - 16:53
An: DShield-ISC/dshield <dshield@noreply.github.com>
Betreff: Re: [DShield-ISC/dshield] Current Cowrie Version not working anymore (#43)

**Comment by jullrich** [comment]
sorry.missed them. merged them now and will try again.

**Comment by gebhard73** [comment]
pls see issues and pr in Github

----- Originale Nachricht -----
Von: Johannes Ullrich <notifications@github.com>
Gesendet: 30.05.17 - 16:53
An: DShield-ISC/dshield <dshield@noreply.github.com>
Betreff: Re: [DShield-ISC/dshield] Current Cowrie Version not working anymore (#43)

**Comment by ktrue** [comment]
I'm trying the update with a backup of my current HP.  Will report results :)

**Comment by gebhard73** [comment]
thank you, appreciate it :-)

**Comment by ktrue** [comment]
I've swapped the updated RPi SDHC for the current one and it's online.
```
pi@TRP2HP:~/dshield $ git pull
remote: Counting objects: 182, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 182 (delta 103), reused 107 (delta 102), pack-reused 73
Receiving objects: 100% (182/182), 45.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), completed with 14 local objects.
From https://github.com/DShield-ISC/dshield
   4618f5e..0c79390  master     -> origin/master
Updating 4618f5e..0c79390
Fast-forward
 .gitignore                 |   4 +-
 README.md                  | 179 +++++++++---
 bin/DShield.py             | 191 +++++++++++--
 bin/install.sh             | 676 +++++++++++++++++++++++++++++++++++++--------
 bin/pifwparser.py          | 110 ++++++++
 bin/spamparser.py          |   5 -
 bin/ufwparser.py           | 134 ++++-----
 etc/init.d/cowrie          |  13 +-
 etc/rsyslog.d/dshield.conf |   2 +-
 9 files changed, 1053 insertions(+), 261 deletions(-)
 create mode 100755 bin/pifwparser.py
pi@TRP2HP:~/dshield $ sudo bin/install.sh
##########################################################################################################
Log /srv/log/install_2017-05-30_193011.log started.

Finished 2017-05-30_201021

Now back online with the updated version.
```
I noticed that my old setup stopped reporting SSH/cowrie on 22-May.  Hopefully, it will start reporting again with this update.
```
Last ssh Log Received: 2017-05-22 20:45:20
Last ssh Firewall Log Received: 2017-05-30 20:15:03
Current Time/Date: 2017-05-30 20:18:51
```

**Comment by gebhard73** [comment]
seems to be fixed (no negative feedback), thanks @ktrue for testing!
