### ISSUE TITLE
0 lines on today's report and bounce, nothing showing for graph and table

### ISSUE THREAD

**Issue by tht1person** [DShield-ISC/dshield#48]
I get the email every 30 mins saying: authorized Userid: [removed]
                          Format: DSHIELD
                        Timezone: +0000
                   Lines in file: 13688
                  Lines rejected: none
Unique lines written to database: 9624
  identical lines are added up on import.
but on my report, it always says 0 for today's report (firewall and ssh) why does it say 0 all the time?
And I also get emails saying that I didn't submit any results. What do I do for that?

Also on "my report" on the graph and table section, no data shows and it's in a constant loop of waiting for data. What can I do to have the data show?

**Comment by jullrich** [comment]
I will have to check your account. (I deleted your account ID above for privacy). Could you please forward a couple of the emails to jullrich - at - sans.edu ?

**Comment by jullrich** [comment]
fixed by expanding on sensor placement in readme file
