### ISSUE TITLE
dshield/bin/status.sh fails to parse ./etc/dshield.conf

### ISSUE THREAD

**Issue by BrianWGray** [DShield-ISC/dshield#5]
dshield/bin/status.sh fails to parse ./etc/dshield.conf

# sh ./status.sh 
status.sh: 1: /etc/dshield.conf: Syntax error: redirection unexpected

**Comment by jullrich** [comment]
Thanks! will fix this shortly. There is an error in the current version of install.sh. If you look at /etc/dshield.conf , you may see that the first line include some XML. Instead, it should just include the numeric userid.


> On Feb 16, 2016, at 9:15 AM, BrianWGray <notifications@github.com> wrote:
> 
> dshield/bin/status.sh fails to parse ./etc/dshield.conf
> 
> sh ./status.sh
> 
> status.sh: 1: /etc/dshield.conf: Syntax error: redirection unexpected
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Don’t miss SANS 2016, March 12-21, in Orlando at the Walt Disney World Dolphin Resort. Choose from more than 35 hands-on Infosec courses taught by SANS incomparable Instructors plus bonus sessions, vendor expo, and challenging Core and DFIR NetWars competitions!
http://www.sans.org/u/avu

**Comment by jullrich** [comment]
Fixed. I also have install.sh check for a dshield.conf that is corrupt as a result (and clean it up)
