### ISSUE TITLE
Error submitting web logs

### ISSUE THREAD

**Issue by gebhard73** [DShield-ISC/dshield#56]
the Python script called by the cron job to submit web logs errors:
```
root@raspberrypi:/srv/dshield# cd /srv/dshield; ./weblogsubmit.py
/etc/dshield.ini
Traceback (most recent call last):
  File "./weblogsubmit.py", line 49, in <module>
    logdata['sip']=d.anontranslateip4((r[1]))
  File "/srv/dshield/DShield.py", line 126, in anontranslateip4
    ip=self.translateip4(ip)
  File "/srv/dshield/DShield.py", line 113, in translateip4
    return self.long2ip4(ip)
  File "/srv/dshield/DShield.py", line 151, in long2ip4
    return socket.inet_ntoa(struct.pack('!I', ip))
struct.error: integer out of range for 'I' format code
```

Note: the pid file `/var/run/weblogparser.pid`has to be deleted to re-run the script.

**Comment by jullrich** [comment]
removed the 'anontansplateip4' part for now. Need to debug further to see what values cause this error.

**Comment by ktrue** [comment]
I'd done an update to the existing honeypot and a fresh build on a separate system after #54 was committed.. both were successful.

I did a git pull and 
sudo cp ~/dshield/srv/weblogsubmit.py /srv/dshield/weblogsubmit.py 
to 'quickie' implement the changed script (install.sh takes a looonnnggg time, as it says).

Also did
 sudo rm /var/run/weblogparser.pid
to clean off the old .pid file.

Now hoping that some weblog submissions will start showing up (for the first time)

**Comment by gebhard73** [comment]
@jullrich quick fix worked for manual invocation, thanks :-)

thanks @ktrue for testing and feedback :-)
