### ISSUE TITLE
No MTA installed

### ISSUE THREAD

**Issue by scott23192** [DShield-ISC/dshield#6]
Logging:
=====
Feb 17 00:00:04 raspberrypi dshield.pl[26707]: submitting dshield logs SHA1 ok
Feb 17 00:00:04 raspberrypi CRON[26697]: (CRON) info (No MTA installed, discarding output)
=====

... would you like for us to install SMTP or is that a future task on your end?

Any preference on what email service to install if done locally?

Thanks!

-Scott

**Comment by jullrich** [comment]
These error messages are not affecting submitting any logs. Some of the cron jobs produce output, and the system will try to send an email attaching the output. I will see if I can redirect some fo the output to files or /dev/null (for the most part, this is likely output intended for debugging when running the script interactively)

**Comment by jullrich** [comment]
going to install postfix with the next update to deal with this error.

**Comment by jullrich** [comment]
the latest version does now install postfix to send email if needed.
