### ISSUE TITLE
No LICENSE file (murky legal waters ahead!)

### ISSUE THREAD

**Issue by da2x** [DShield-ISC/dshield#62]
Please create a LICENSE file to clarify the legal status of the codebase. (Need help [choosing a license](https://choosealicense.com/licenses/)?.)

I license my own contribution, commit 39ad0a1ee86ee7aa4f3b55a87ecb04c52e2d5227, in the public domain so that it may be licensed properly as part of the project.

The [other contributors](https://github.com/DShield-ISC/dshield/graphs/contributors) should be contacted to seek permission before a license is applied to their contributions. If they don’t agree to a license then their contributions should be removed before applying a license.

**Comment by jullrich** [comment]
will add GPL 2.0 license. (I thought I already did that...)
