### ISSUE TITLE
Verify installation and share log data

### ISSUE THREAD

**Issue by HenrikssonAnders** [DShield-ISC/dshield#66]
Hi

Yesterday I set up a raspberry pi with dshield and the installation went all well according to the log file.

I can in the log files /var/log/dshield see that log entrys are generated as the Pi is exposed to "raw" Internet.

When I enter my site at dshield to see my reports I don´t see any reports from me.

How often does the pi send the reports to the site or am I missing something here?

/Anders

**Comment by gebhard73** [comment]
Hi,

logs are send twice an hour, see `/etc/cron.d/dshield`

You can try running the script `/srv/dshield/dshield.pl` manually (as root).

What does `/home/pi/install/dshield/bin/status.sh` show you?

**Comment by HenrikssonAnders** [comment]
Hi
/home/pi/install/dshield/bin/status.sh says that API-key is wrong, faild verification and that I should try again in 5 min.
Have checked dshield.conf and the API-key is correct, same as on my account page.

I restarted the install.sh script and now the API-key verification fails.

I do copy and paste the API-key so that I don´t do any miss spellings or incorrect keystrokes.

**Comment by gebhard73** [comment]
the only thing which comes to my mind are whitespaces / blanks ... but then the install script should also have failed ...
will have to wait for @jullrich to investigate further

**Comment by jullrich** [comment]
on your raspberry pi, can you please check if the API key is correct in /etc/dshield.conf and /etc/dshield.ini ? Please send me your account email address directly so I can check your account as well for any anomaly (jullrich@sans.edu) .

thanks.

**Comment by jullrich** [comment]
problem solved by reinstalling software.
