### ISSUE TITLE
Honeypot Ports

### ISSUE THREAD

**Issue by dsplice** [DShield-ISC/dshield#69]
Just wondering if it would be beneficial to change the ports used by the honeypot (2222 for ssh, 8000 for http etc) to the defaults?  Since the device is only to be used for a honeypot, I do not see any harm in using those well known ports.  Could be missing something though too, totally possible  :P

**Comment by jullrich** [comment]
Running the honeypot on a high port allows us to run the software as a "normal user" without having to worry about releasing privileges. So in short: it is a bit safer to run it on 2222 vs 22.
