### ISSUE TITLE
No new log

### ISSUE THREAD

**Issue by Krypt0ni8** [DShield-ISC/dshield#7]
Why you'd have to have at least one log under /var/log/dshield for dshield.pl to run?

**Comment by jullrich** [comment]
dshield.pl parses /var/log/dshield. Without the file, there is nothing to do for dshield.pl . The install script configures a firewall that will log all inbound connections. rsyslog is then configured to write these logs to /var/log/dshield . It is highly unusual if you don't have any logs in /var/log/dshield after running the system for a couple hours exposed to the internet. If you don't have any logs, you likely don't have it exposed to open internet traffic and a router may be blocking traffic. You can also use the "status.sh" script in the 'dshield/bin' folder to check if you are submitting logs. Run "sudo dshield/bin/status.sh"  to check.
