### ISSUE TITLE
New Raspbian Release ("Stretch", August 2017)

### ISSUE THREAD

**Issue by jullrich** [DShield-ISC/dshield#70]
Just saw that a new version of Raspbian was released. Opening this issue for any related problems. (downloading it right now to test)

**Comment by dsplice** [comment]
Version has changed from 8 to 9.  I have put in a pull request for the change.

At the spot where it asks for the email and api key, no dialog box comes up, so the case statement never completes successfully ($response is always blank) resulting in an infinite loop at while apikeyok part.

**Comment by jullrich** [comment]
Thanks. Will see what is going on with the API key dialog.

**Comment by dsplice** [comment]
Manually entered in information in the script.  Further dialog boxes seem to be affected as well (EG default interface).

**Comment by dsplice** [comment]
Ok, Raspbian Stretch Lite (haven't tested the full version) is missing the dialog package.  A sudo apt-get install dialog appears to have solved it.  

Still working through some further issues.

**Comment by dsplice** [comment]
In Raspbian Sketch (and modern Debian based systems), interface names have changed.  Local lan interface is now named with a 15 character name.  Issue is located in the dialog options.  I will put in a pull request to fix.

**Comment by dsplice** [comment]
For some reason several packages do not install via the script.  When first installing git, I added several packages (sudo apt-get install git dialog virtualenv default-libmysqlclient-dev libpython-dev libffi-dev libssl-dev)  The install script (along with the pull requests) then completes successfully under Raspbian Stretch Lite.

**Comment by dsplice** [comment]
Issue was the apt-get install failed due to missing libmysqlclient-dev package.  Subtitute package default-libmysqlclient-dev is available and works.  I have put in a pull request for this change.  Fully tested on Raspberry Pi 3 with Raspbian Stretch Lite.

**Comment by jullrich** [comment]
seems to be fixed now. Maintaining backward compatibility for now.
