### ISSUE TITLE
Enhancement: DShield.org site improvement on information related to user/pass attemps

### ISSUE THREAD

**Issue by killamjr** [DShield-ISC/dshield#75]
Problem: Something I've noticed when browsing the login attempts in the raw dshield data is lots username and password combos many related to mirai are obvious, but some are a bit harder to figure out.

Possible Solution: allow click through to a page with or additional column about possible applications of the username/password combo. Creating an individual page for each combo could allow for comments about possible sources.

Example:
User   | Password           | Comment
admin | 7ujMko0admin  | Mirai Botnet Scanning
admin | pfsense              | Default PFSENSE Login
pi        | raspberry           | Default Raspberry Pi Login

**Comment by jullrich** [comment]
as a quick fix, I added a link to the password page from the text based password list. But this needs a bit more work, so leaving this open. Probably needs another page that summarizes the submissions better.

**Comment by jullrich** [comment]
improved this recently.
