### ISSUE TITLE
install script says I changed my ssh port, but I didn't

### ISSUE THREAD

**Issue by jullrich** [DShield-ISC/dshield#79]
The install script displays the "Congrats, you already changed your sshd port to something other than 22" message, but my ssh port has not been changed yet.

**Comment by jullrich** [comment]
Looks like the problem is that the "Port" line is commented out in sshd_Config, but the script expects the line to start with "Port".

**Comment by jullrich** [comment]
committed possible fix.

**Comment by dsplice** [comment]
Just tested against the latest repo and Sept Raspbian Lite (Sept 19, 2017 at about 16:00 UTC).  All worked as expected.
