### ISSUE TITLE
SSHD config not setting management VLAN

### ISSUE THREAD

**Issue by rydogg1** [DShield-ISC/dshield#8]
Posted this in the comments on initial ISC diary post:

It looks like the management sshd port is listening on all interfaces:

pi@raspberrypi:~ $ netstat -an| grep 2222
tcp 0 0 0.0.0.0:12222 0.0.0.0:* LISTEN 
tcp 0 0 192.168.1.20:12222 192.168.1.147:56176 ESTABLISHED
tcp6 0 0 :::12222 :::* LISTEN 

If the management port is to be 12222 then it needs to be bound in the sshd_config. The ListenAddress is not set on a fresh install of Jessie; so not sure if it needs to be preset before the script changes the ssh port.

//What ports, IPs and protocols we listen for
Port 12222
//Use these options to restrict which interfaces/protocols sshd will bind to
#ListenAddress ::
#ListenAddress 0.0.0.0

**Comment by jullrich** [comment]
the listen address is left open on purpose. only the port is altered. There isn't really a "management vlan". The "trusted network" in the configuration is only used so logs originating from the network will not be reported. The sensor is assumed to only have one interface and one IP address (its a honeypot, not really a sensor in the classic IDS sense)
