### ISSUE TITLE
AWS Stretch AMI EC2 install issues

### ISSUE THREAD

**Issue by thinkersailor** [DShield-ISC/dshield#80]
When installing on an AWS Stretch AMI (from https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch): debian-stretch-hvm-x86_64-gp2-2017-08-31-64407), I found a number of issues. 

-/etc/os-release ID is 'debian' not 'raspbian' (checked in install.sh around lines 274-293). I fixed it by editing /etc/os-release but probably better to make the install script more aware.

-sshd_config has Port = 22 commented out. NOTE: this is already tracked in issue 79

-several packages were missing from the default install of the AMI - dialog curl zip gcc python-dev default-libmysqlclient-dev libswitch-perl libwww-perl   

With these three issues addressed, the install proceeded normally.

**Comment by jullrich** [comment]
Ubuntu 18.04 should now be supported with the latest update. I will hold off on supporting AMI Linux images better (running into some issues with ssh/iptables)
