### ISSUE TITLE
Enhance firewall starting and closing

### ISSUE THREAD

**Issue by freekdk** [DShield-ISC/dshield#82]
I made a few files for using systemd for starting the firewall at boot time, after network startup and shutdown. It replaces if-pre-up.d/dshield
File lib/systemd/system/dshieldfirewall_init.service
`# This file is part of the package dshield`
`#`
`# Used to start the firewall before the network starts`
`#`
`# Designed following the openSUSE firewall ideas`
`# by Freek de Kruijf`
`#`

`[Unit]`
`Description=Dshield firewall phase 1`
`Before=network.service`
`DefaultDependencies=false'`
`Requires=sysinit.target`
`After=sysinit.target`
`RequiresMountsFor=/dev/shm`
`Conflicts=firewalld.service`

`[Service]`
`ExecStart=/usr/sbin/iptables-restore /etc/network/iptables-init`
`RemainAfterExit=true`
`Type=oneshot`

`[Install]`
`WantedBy=multi-user.target`
`Also=dshieldfirewall.service`

File /etc/network/iptables-init
`# Generated by iptables-save v1.6.1 on Fri Sep 22 13:32:04 2017`
`*filter`
`:INPUT DROP [0:0]`
`:FORWARD DROP [0:0]`
`:OUTPUT ACCEPT [56:5624]`
`:reject_func - [0:0]`
`-A INPUT -i lo -j ACCEPT`
`-A INPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT`
`-A INPUT -p icmp -m conntrack --ctstate RELATED -j ACCEPT`
`-A INPUT -p udp -m udp --dport 5353 -m pkttype --pkt-type multicast -j ACCEPT`
`-A OUTPUT -o lo -j ACCEPT`
`-A reject_func -p tcp -j REJECT --reject-with tcp-reset`
`-A reject_func -p udp -j REJECT --reject-with icmp-port-unreachable`
`-A reject_func -j REJECT --reject-with icmp-proto-unreachable`
`COMMIT`
`# Completed on Fri Sep 22 13:32:04 2017`
File lib/systemd/system/dshieldfirewall.service
`# This file is part of the package dshield`
`#`
`# Used to start the firewall with honeypot rules`
`#`
`# Designed following the openSUSE firewall ideas`
`# by Freek de Kruijf`
`#`

`[Unit]`
`Description=DShield firewall phase 2`
`After=network.target nfs-client.target ypbind.service nfs-server.service rpcbind.service dshieldfirewall_init.service`
`Wants=dshieldfirewall_init.service`
`Conflicts=firewalld.service`

`[Service]`
`ExecStart=/usr/sbin/iptables-restore /etc/network/iptables`
`ExecStop=/usr/sbin/iptables-restore /etc/network/iptables-stop`
`RemainAfterExit=true`
`Type=oneshot`

`[Install]`
`WantedBy=multi-user.target`
`Alias=dshieldfirewall_setup.service`
`Also=dshieldfirewall_init.service`

The mentioned file /etc/network/iptables is generated by the install script.
File /etc/network/iptables-stop:
`# Generated by iptables-save v1.6.1 on Fri Sep 22 13:34:48 2017`
`*filter`
`:INPUT ACCEPT [0:0]`
`:FORWARD ACCEPT [0:0]`
`:OUTPUT ACCEPT [0:0]`
`COMMIT`
`# Completed on Fri Sep 22 13:34:48 2017`

The firewall gets started by enabling with "systemctl enable dshieldfirewall.service" and a reboot.

**Comment by gebhard73** [comment]
any really drawbacks from the way we do it using if-pre-up.d?

from a first glance we may be more portable using the if-pre-up.d approach, what do you think?

**Comment by freekdk** [comment]
It is not portable to openSUSE, so I copied the method from openSUSE and tested it also in Raspbian. It works there as well. This method protects the system already during the boot process, because the first service is started before the network starts.

**Comment by freekdk** [comment]
I designed the script install-opensuse.sh using install.sh which can be used both on Raspbian and openSUSE for Raspberry Pi (1B, 2B and 3B). My honeypot runs currently on a 1B, previously on a 2B.

**Comment by freekdk** [comment]
The install.sh script does have the enhancement in it for openSUSE. It needs some changes in conditions to enable it for other systems as well.

**Comment by freekdk** [comment]
I will test and implement the change from iptables to nftables in Raspbian when my changes for openSUSE are accepted. This will implement this enhancement also for Rasbian.

**Comment by freekdk** [comment]
Implemented in the openSUSE version and when using nptables in rasbian and debian version 11.
