### ISSUE TITLE
Enhance starting cowrie using systemd

### ISSUE THREAD

**Issue by freekdk** [DShield-ISC/dshield#83]
I designed a replacement for /etc/init.d/cowrie to start it using systemd.
File lib/systemd/system/cowrie.service:
```
# This file is part of package dshield.
#
# Description:
#
#  Used to start/stop the cowrie honeypot
#

[Unit]
Description=Honeypot cowrie service
After=network.target time-sync.target multi-user.target

[Service]
Type=forking
PIDFile=/srv/cowrie/var/run/cowrie.pid
TimeoutSec=300
User=cowrie
ExecStartPre=-/bin/echo 'Starting cowrie' 
ExecStart=/srv/cowrie/bin/cowrie start
ExecStop=/srv/cowrie/bin/cowrie stop
ExecStopPost=-/bin/echo 'Stopping cowrie'

[Install]
WantedBy=multi-user.target
```
This file needs to be enabled by "systemctl enable cowrie.service"
This also means that the file etc/cron.hourly/cowrie should be replaced by:
```
#!/bin/sh
systemctl stop cowrie.service
sleep 10
# delete small logs (likely irrelevant) and logs older then a week
find /srv/cowrie/log/tty/ -size -1000c -name '*.log' -delete
find /srv/cowrie/log/tty/ -ctime +7 -name '*.log' -delete
systemctl start cowrie.service
```

**Comment by freekdk** [comment]
There is already a file cowrie.service after downloading cowrie, done in the install.sh script.
So in the install.sh script the following lines are needed:
do_copy /srv/cowrie/doc/systemd/cowrie.service /usr/lib/systemd/system/cowrie.service 644
`run 'systemctl enable cowrie.service'`
And to adapt a few other files:
`run 'sed -i "s/\/etc.*$/systemctl restart cowrie.service/" /etc/logrotate.d/cowrie'`
`run 'sed -i "s/>.*$/cowrie.service/g" /etc/cron.hourly/cowrie'`
Obviously the sed can also be done on the original files and saving the result at the final destination.

**Comment by gebhard73** [comment]
is this still valid? 
perhaps I can set some time aside to have a look into this ...

**Comment by freekdk** [comment]
Yes. It is replacing what is now in /etc/init.d/ to start cowrie. That's all. So that can be deleted.

**Comment by jullrich** [comment]
done.
