### ISSUE TITLE
Tweaks to install.sh for easier installation on Debian in AWS

### ISSUE THREAD

**Issue by thinkersailor** [DShield-ISC/dshield#85]
Standard AWS Debian AMI does not come with curl installed. Need to add to list of packages installed.

Also, on the AWS Debian AMI, if you cat /etc/os-release, the ID=debian. This causes the install script to fail. I have been fixing by editing os-release and changing debian to raspbian but it seems like we could just add debian to the list of os versions checked in install.sh and everything would be fine. I'm just too lazy/busy to figure out the bash syntax to make it work. 

With these two changes, the honeypot has installed on the Debian Stretch AMI flawlessly.

**Comment by jullrich** [comment]
closing this (fixed . see above)
