### ISSUE TITLE
Web.py hardcodes targetip

### ISSUE THREAD

**Issue by thinkersailor** [DShield-ISC/dshield#86]
Just adding this issue in here to be tracked/fixed sometime. Currently Web.py statically assigns a variable called 'targetip' to 0.0.0.0 (as of this writing it's on line 92). 

This value is then submitted as data via weblogsubmit.py but since it's always 0.0.0.0 as the destination IP, it's not very useful. Should be addressed by either recording the actual destination IP properly, or not submitting it to DShield as wasted bits.

**Comment by jullrich** [comment]
fixed by thinkersailor (see above)
