### ISSUE TITLE
MySQL error on update/install.sh

### ISSUE THREAD

**Issue by rydogg1** [DShield-ISC/dshield#9]
Updated via git pull command, ran an update install.sh, then the install.sh script noticed that the MySQL database was already created and asked the question to reinitialize the MySQL.  On that this error showed:

ERROR 1049 (42000): Unknown database 'create schema cowrie'

**Comment by Krypt0ni8** [comment]
Going with a brand new MySQL instance did the trick.

**Comment by jullrich** [comment]
fixed. (syntax error in sql comment)
