### ISSUE TITLE
SSH Logs not being submitted

### ISSUE THREAD

**Issue by bdmeyer** [DShield-ISC/dshield#91]
I reviewed the information written here: [New Feature: "Live" SSH Brute Force Logs and New Kippo Client](https://isc.sans.edu/forums/diary/New+Feature+Live+SSH+Brute+Force+Logs+and+New+Kippo+Client/18433.)

 It points to the Kippo.pl script which states:

> This script has become somewhat obsolete. The newer version of 
> "Kippo", "Cowrie", now includes the ability to submit logs to 
> dshield. 
> I recommend you use cowrie instead of kippo and take advantage of
> its built in DShield submission feature

So I am not using the kippo.pl script.
Is there anything I can do to enable the ssh info to become uploaded? I have not found docs for this. FWIW the Basic Web server and 404 logs aren't working that is discussed in the TODO (Web.py) which may not even be implemented, since it is in the TODO's. 
-= BDM

**Comment by gebhard73** [comment]
out of the box the following should be working:

- firewall logs
- ssh logs (cowrie)
- telnet logs (cowrie9
- 404 logs

**Comment by bdmeyer** [comment]
I opened ticket #90, which perhaps has something to do with my issue.
I show no 404 logs, no ssh logs (Referring to at ISC web site) have no idea about telnet logs, I don't think I've ever seen that in the Dshield reports before.

**Comment by gebhard73** [comment]
If you haven't successfully installed it (meaning #90 is closed) then nothing will show up in dshield portal ;-)

telnet will be aggregated into ssh (maybe should be renamed into "credentials" or so in dshield portal)

**Comment by bdmeyer** [comment]
I am getting my portscan info on DShield. Just no SSH or 404.

> For 2017-10-31 you submitted 7877 packets from 162 sources hitting 1 targets.

**Comment by bdmeyer** [comment]
After getting a successful install using the tip from the Cowrie site, 404 and ssh are working now.
