### ISSUE TITLE
remove mysql dependency

### ISSUE THREAD

**Issue by jullrich** [DShield-ISC/dshield#94]
I think we can just move everything to sqlite. No need to carry around mysql. it is currently only used for cowrie.

**Comment by jullrich** [comment]
started "nomysql" branch for this

**Comment by uberlance** [comment]
This seems to be related (hence a comment instead of a new issue).

InnoDB does appear to be getting pruned or managed.  Moving away from mysql should clear this up, but as of now the InnoDB file is consuming ~25% of the 8GB card I am using with the pi.

ETA on merging the nomysql branch?

**Comment by jullrich** [comment]
just released an update that I think removed the last dependency (v 0.48)
