### ISSUE TITLE
/srv/cowrie/log needs automatic grooming...

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#98]
One issue is the files in /srv/cowrie/log are not groomed ( combined to a daily log, gzipped with separate files removed).  As a result, the filesystem space is continually being consumed.

Is there a /etc/rsyslog.d config that would do that?  Can it be added to the base distribution?

Help.. drowning is excess cowrie log files...

**Comment by gebhard73** [comment]
interesting - my logs are handled by logrotate using
/etc/logrotate.d/cowrie:
```
/srv/cowrie/log/cowrie.log /srv/cowrie/log/cowrie.json
{
        rotate 7
        daily
        missingok
        compress
        postrotate
                /etc/init.d/cowrie restart
        endscript
}
```
Can you please point out what isn't working on your installaion? Thanks.

**Comment by ktrue** [comment]
Yes, I have exactly the same in /etc/logrotate.d/cowrie.

See the attached ls -l for /srv/cowrie/log

Why so many cowrie.log.DDD files?  Why the uncompressed cowrie.json.YYYY-MM-DD files?

There are a few .gz files in the directory (like cowrie.log.N.gz ) but a lot more cleanup is needed on a daily basis to prevent the /srv/cowrie/log are from expanding to fill all available disk space.
[srv-cowrie-log.txt](https://github.com/DShield-ISC/dshield/files/1584298/srv-cowrie-log.txt)

**Comment by gebhard73** [comment]
this seems to be a cowrie issue ... I can't find any reason for the files you mentioned, sorry.

**Comment by ktrue** [comment]
I found both /srv/cowrie/log and /srv/cowrie/log/tty directories were accumulating *lots* of files.  I decided that 3 day retention was enough to prevent filling all space available, so ran the following commands:
```
sudo find /srv/cowrie/log/ -type f -regextype sed -regex '.*cowrie\.log\.[0-9]\{1,3\}' -mtime +3 -exec rm {} \;
sudo find /srv/cowrie/log/ -type f -regextype sed -regex '.*cowrie\.json\.[0-9]\{4\}_[0-9]\{2\}_[0-9]\{2\}' -mtime +3 -exec gzip -9 {} \;
sudo find /srv/cowrie/log/tty -type f -regextype sed -regex '.*\.log' -mtime +3 -exec rm {} \;
```
The middle on just gzips the daily files while the first and last one removes the files over 3 days old.

I'm going to do this weekly (until the cowrie automatic cleanup is 'fixed' in the distribution).

**Comment by gebhard73** [comment]
thanks for posting the workaround - I'd suggest keeping this issue open as long as Cowrie / twisted have incorporated a solution into their installation files (or suggested another handling)

**Comment by ktrue** [comment]
I added one more cleanup to the /srv/cowrie/dl directory  -- now it seems to handle all the files that were previously 'ungroomed'

```
sudo find /srv/cowrie/log/ -type f -regextype sed -regex '.*cowrie\.log\.[0-9]\{1,3\}' -mtime +3 -exec rm {} \;
sudo find /srv/cowrie/log/ -type f -regextype sed -regex '.*cowrie\.json\.[0-9]\{4\}_[0-9]\{2\}_[0-9]\{2\}' -mtime +3 -exec gzip -9 {} \;
sudo find /srv/cowrie/log/tty -type f -regextype sed -regex '.*\.log' -mtime +3 -exec rm {} \;
sudo find /srv/cowrie/dl -type f -regextype sed -regex '.*' -mtime +3 -exec rm {} \;
```

**Comment by jullrich** [comment]
looks indeed like cowrie's own log rotation is interfering with logrotate. Will take a look at it.

**Comment by freekdk** [comment]
The logrotate is not properly working, it only concerns the two mentioned files.
However there is /etc/cron.hourly/cowrie, which only needs two more lines
```
find /srv/cowrie/log/ -mtime +7 -name 'cowrie.*' -delete
find /srv/cowrie/dl/ -mtime +7 -name '[0-9,a-z]*' -delete
```
I kept the retention time on 7 days, otherwise change the 7 in this file to the number of days you want.

**Comment by jullrich** [comment]
the issue is I think that cowrie does its own log rotation which is not "compatible" with logrotate. The "find" seem to be the only option at this point. I will be watching my current instance to investigate. logrotate may actually be counter productive in this case.

**Comment by jullrich** [comment]
the text log "cowrie.log.123" is rotated by cowrie. I am just deleting old logs now. The "json" log is not rotated by cowrie and I left that up to logrotate.
